# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from soil_services import AxialMosherSandService_pb2 as soil__services_dot_AxialMosherSandService__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in soil_services/AxialMosherSandService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AxialMosherSandServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMosherSandProperties = channel.unary_unary(
                '/grpc_axial_mosher_sand.AxialMosherSandService/GetMosherSandProperties',
                request_serializer=soil__services_dot_AxialMosherSandService__pb2.GetMosherSandRequest.SerializeToString,
                response_deserializer=soil__services_dot_AxialMosherSandService__pb2.GetMosherSandResponse.FromString,
                _registered_method=True)
        self.SetMosherSandProperties = channel.unary_unary(
                '/grpc_axial_mosher_sand.AxialMosherSandService/SetMosherSandProperties',
                request_serializer=soil__services_dot_AxialMosherSandService__pb2.SetMosherSandRequest.SerializeToString,
                response_deserializer=soil__services_dot_AxialMosherSandService__pb2.SetMosherSandResponse.FromString,
                _registered_method=True)


class AxialMosherSandServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMosherSandProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMosherSandProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AxialMosherSandServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMosherSandProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMosherSandProperties,
                    request_deserializer=soil__services_dot_AxialMosherSandService__pb2.GetMosherSandRequest.FromString,
                    response_serializer=soil__services_dot_AxialMosherSandService__pb2.GetMosherSandResponse.SerializeToString,
            ),
            'SetMosherSandProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMosherSandProperties,
                    request_deserializer=soil__services_dot_AxialMosherSandService__pb2.SetMosherSandRequest.FromString,
                    response_serializer=soil__services_dot_AxialMosherSandService__pb2.SetMosherSandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_axial_mosher_sand.AxialMosherSandService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc_axial_mosher_sand.AxialMosherSandService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AxialMosherSandService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMosherSandProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_axial_mosher_sand.AxialMosherSandService/GetMosherSandProperties',
            soil__services_dot_AxialMosherSandService__pb2.GetMosherSandRequest.SerializeToString,
            soil__services_dot_AxialMosherSandService__pb2.GetMosherSandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMosherSandProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_axial_mosher_sand.AxialMosherSandService/SetMosherSandProperties',
            soil__services_dot_AxialMosherSandService__pb2.SetMosherSandRequest.SerializeToString,
            soil__services_dot_AxialMosherSandService__pb2.SetMosherSandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
