# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: soil_services/LateralDryStiffClayService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'soil_services/LateralDryStiffClayService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.soil_services/LateralDryStiffClayService.proto\x12\x1bgrpc_lateral_dry_stiff_clay\"=\n\x16GetDryStiffClayRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07soil_id\x18\x02 \x01(\t\"l\n\x17GetDryStiffClayResponse\x12Q\n\x14\x64ry_stiff_clay_props\x18\x01 \x01(\x0b\x32\x33.grpc_lateral_dry_stiff_clay.DryStiffClayProperties\"\xa2\x01\n\x16SetDryStiffClayRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x0f\n\x07soil_id\x18\x03 \x01(\t\x12Q\n\x14\x64ry_stiff_clay_props\x18\x04 \x01(\x0b\x32\x33.grpc_lateral_dry_stiff_clay.DryStiffClayProperties\"\x19\n\x17SetDryStiffClayResponse\"O\n\x16\x44ryStiffClayProperties\x12\x1a\n\x12shear_strength_DSC\x18\x01 \x01(\x01\x12\x19\n\x11strain_factor_DSC\x18\x02 \x01(\x01\x32\xb2\x02\n\x1aLateralDryStiffClayService\x12\x88\x01\n\x19GetDryStiffClayProperties\x12\x33.grpc_lateral_dry_stiff_clay.GetDryStiffClayRequest\x1a\x34.grpc_lateral_dry_stiff_clay.GetDryStiffClayResponse\"\x00\x12\x88\x01\n\x19SetDryStiffClayProperties\x12\x33.grpc_lateral_dry_stiff_clay.SetDryStiffClayRequest\x1a\x34.grpc_lateral_dry_stiff_clay.SetDryStiffClayResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'soil_services.LateralDryStiffClayService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDRYSTIFFCLAYREQUEST']._serialized_start=79
  _globals['_GETDRYSTIFFCLAYREQUEST']._serialized_end=140
  _globals['_GETDRYSTIFFCLAYRESPONSE']._serialized_start=142
  _globals['_GETDRYSTIFFCLAYRESPONSE']._serialized_end=250
  _globals['_SETDRYSTIFFCLAYREQUEST']._serialized_start=253
  _globals['_SETDRYSTIFFCLAYREQUEST']._serialized_end=415
  _globals['_SETDRYSTIFFCLAYRESPONSE']._serialized_start=417
  _globals['_SETDRYSTIFFCLAYRESPONSE']._serialized_end=442
  _globals['_DRYSTIFFCLAYPROPERTIES']._serialized_start=444
  _globals['_DRYSTIFFCLAYPROPERTIES']._serialized_end=523
  _globals['_LATERALDRYSTIFFCLAYSERVICE']._serialized_start=526
  _globals['_LATERALDRYSTIFFCLAYSERVICE']._serialized_end=832
# @@protoc_insertion_point(module_scope)
