# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: soil_services/LateralMassiveRockService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'soil_services/LateralMassiveRockService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-soil_services/LateralMassiveRockService.proto\x12\x19grpc_lateral_massive_rock\"<\n\x15GetMassiveRockRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07soil_id\x18\x02 \x01(\t\"f\n\x16GetMassiveRockResponse\x12L\n\x12massive_rock_props\x18\x01 \x01(\x0b\x32\x30.grpc_lateral_massive_rock.MassiveRockProperties\"\x9c\x01\n\x15SetMassiveRockRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x0f\n\x07soil_id\x18\x03 \x01(\t\x12L\n\x12massive_rock_props\x18\x04 \x01(\x0b\x32\x30.grpc_lateral_massive_rock.MassiveRockProperties\"\x18\n\x16SetMassiveRockResponse\"\xbd\x01\n\x15MassiveRockProperties\x12\x18\n\x10use_Erm_MassRock\x18\x01 \x01(\x08\x12\x13\n\x0bmi_MassRock\x18\x02 \x01(\x01\x12\x14\n\x0cGSI_MassRock\x18\x03 \x01(\x01\x12\x14\n\x0cUCS_MassRock\x18\x04 \x01(\x01\x12\x13\n\x0b\x45i_MassRock\x18\x05 \x01(\x01\x12\x14\n\x0c\x45rm_MassRock\x18\x06 \x01(\x01\x12\x1e\n\x16poisson_ratio_MassRock\x18\x07 \x01(\x01\x32\xa3\x02\n\x19LateralMassiveRockService\x12\x81\x01\n\x18GetMassiveRockProperties\x12\x30.grpc_lateral_massive_rock.GetMassiveRockRequest\x1a\x31.grpc_lateral_massive_rock.GetMassiveRockResponse\"\x00\x12\x81\x01\n\x18SetMassiveRockProperties\x12\x30.grpc_lateral_massive_rock.SetMassiveRockRequest\x1a\x31.grpc_lateral_massive_rock.SetMassiveRockResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'soil_services.LateralMassiveRockService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETMASSIVEROCKREQUEST']._serialized_start=76
  _globals['_GETMASSIVEROCKREQUEST']._serialized_end=136
  _globals['_GETMASSIVEROCKRESPONSE']._serialized_start=138
  _globals['_GETMASSIVEROCKRESPONSE']._serialized_end=240
  _globals['_SETMASSIVEROCKREQUEST']._serialized_start=243
  _globals['_SETMASSIVEROCKREQUEST']._serialized_end=399
  _globals['_SETMASSIVEROCKRESPONSE']._serialized_start=401
  _globals['_SETMASSIVEROCKRESPONSE']._serialized_end=425
  _globals['_MASSIVEROCKPROPERTIES']._serialized_start=428
  _globals['_MASSIVEROCKPROPERTIES']._serialized_end=617
  _globals['_LATERALMASSIVEROCKSERVICE']._serialized_start=620
  _globals['_LATERALMASSIVEROCKSERVICE']._serialized_end=911
# @@protoc_insertion_point(module_scope)
