import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_8dae6d49a9(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_b12d3eefc6():spartaqube_cli.list()
@app.command()
def sparta_87cd4b4fc2():spartaqube_cli.sparta_87cd4b4fc2()
@app.command()
def sparta_cb0641b2de():print('Hello world!')
if __name__=='__main__':app()