from redis import Redis
from strideutils.stride_config import config as config, get_env_or_raise as get_env_or_raise, get_redis_password_env_var as get_redis_password_env_var

class RedisClient:
    def __init__(self, db_name_or_names: list[str] | str | None = None) -> None: ...
    def get_db(self, name: str | None = None) -> Redis: ...
    def get(self, key: str, db_name: str | None = None) -> str | None: ...
    def get_multiple_keys(self, keys: list[str], db_name: str | None = None) -> list[str | None]: ...
    def get_all_keys(self, db_name: str | None = None) -> list[str]: ...
    def set(self, key: str, val: str, db_name: str | None = None) -> None: ...
    def set_keys(self, dict_to_upload: dict[str, str], db_name: str | None = None, prefix: str = '') -> None: ...
    def get_list(self, key: str, db_name: str | None = None, start: int = 0, end: int = -1) -> list[str]: ...
    def create_list(self, key: str, values: list[str], db_name: str | None = None) -> None: ...
    def append_list(self, key: str, values: str | list[str], db_name: str | None = None) -> None: ...
