# coding: utf-8

# flake8: noqa
"""
    Selling Partner API for Data Kiosk

    The Selling Partner API for Data Kiosk lets you submit GraphQL queries from a variety of schemas to help selling partners manage their businesses.

    The version of the OpenAPI document: 2023-11-15
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from spapi.models.datakiosk_v2023_11_15.create_query_response import CreateQueryResponse
from spapi.models.datakiosk_v2023_11_15.create_query_specification import CreateQuerySpecification
from spapi.models.datakiosk_v2023_11_15.error import Error
from spapi.models.datakiosk_v2023_11_15.error_list import ErrorList
from spapi.models.datakiosk_v2023_11_15.get_document_response import GetDocumentResponse
from spapi.models.datakiosk_v2023_11_15.get_queries_response import GetQueriesResponse
from spapi.models.datakiosk_v2023_11_15.get_queries_response_pagination import GetQueriesResponsePagination
from spapi.models.datakiosk_v2023_11_15.query import Query
from spapi.models.datakiosk_v2023_11_15.query_pagination import QueryPagination
