from dataclasses import dataclass

from strideutils import stride_requests as stride_requests
from strideutils.stride_config import config as config

WALLET_SETUP_COMMAND: str

@dataclass
class TxResponse:
    stdout: dict
    stderr: str
    tx_hash: str = ...
    success: bool = ...
    code: int | None = ...
    tx_response: dict | None = ...
    raw_log: str | None = ...

def restore_wallet(account_name: str = 'wallet', mnemonic_var: str = 'MNEMONIC', binary: str = 'strided'): ...
def execute_tx(command: str, api_endpoint: str = ...) -> TxResponse: ...
