"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .ticketstatus import TicketStatus
from moovio_sdk.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class WebhookDataTicketUpdatedTypedDict(TypedDict):
    account_id: str
    ticket_id: str
    status: TicketStatus


class WebhookDataTicketUpdated(BaseModel):
    account_id: Annotated[str, pydantic.Field(alias="accountID")]

    ticket_id: Annotated[str, pydantic.Field(alias="ticketID")]

    status: TicketStatus
