# coding: utf-8

"""
    Selling Partner API for Supply Sources

    Manage configurations and capabilities of seller supply sources.

    The version of the OpenAPI document: 2020-07-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import pprint
import re  # noqa: F401

import six

from spapi.configuration import Configuration


class OutboundCapability(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_supported': 'bool',
        'operational_configuration': 'OperationalConfiguration',
        'return_location': 'ReturnLocation',
        'delivery_channel': 'DeliveryChannel',
        'pickup_channel': 'PickupChannel',
    }

    attribute_map = {
        'is_supported': 'isSupported',
        'operational_configuration': 'operationalConfiguration',
        'return_location': 'returnLocation',
        'delivery_channel': 'deliveryChannel',
        'pickup_channel': 'pickupChannel',
    }

    def __init__(self, is_supported=None, operational_configuration=None, return_location=None, delivery_channel=None, pickup_channel=None, _configuration=None):  # noqa: E501
        """OutboundCapability - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._is_supported = None
        self._operational_configuration = None
        self._return_location = None
        self._delivery_channel = None
        self._pickup_channel = None
        self.discriminator = None

        if is_supported is not None:
            self.is_supported = is_supported
        if operational_configuration is not None:
            self.operational_configuration = operational_configuration
        if return_location is not None:
            self.return_location = return_location
        if delivery_channel is not None:
            self.delivery_channel = delivery_channel
        if pickup_channel is not None:
            self.pickup_channel = pickup_channel

    @property
    def is_supported(self):
        """Gets the is_supported of this OutboundCapability.  # noqa: E501


        :return: The is_supported of this OutboundCapability.  # noqa: E501
        :rtype: bool
        """
        return self._is_supported

    @is_supported.setter
    def is_supported(self, is_supported):
        """Sets the is_supported of this OutboundCapability.


        :param is_supported: The is_supported of this OutboundCapability.  # noqa: E501
        :type: bool
        """

        self._is_supported = is_supported

    @property
    def operational_configuration(self):
        """Gets the operational_configuration of this OutboundCapability.  # noqa: E501


        :return: The operational_configuration of this OutboundCapability.  # noqa: E501
        :rtype: OperationalConfiguration
        """
        return self._operational_configuration

    @operational_configuration.setter
    def operational_configuration(self, operational_configuration):
        """Sets the operational_configuration of this OutboundCapability.


        :param operational_configuration: The operational_configuration of this OutboundCapability.  # noqa: E501
        :type: OperationalConfiguration
        """

        self._operational_configuration = operational_configuration

    @property
    def return_location(self):
        """Gets the return_location of this OutboundCapability.  # noqa: E501


        :return: The return_location of this OutboundCapability.  # noqa: E501
        :rtype: ReturnLocation
        """
        return self._return_location

    @return_location.setter
    def return_location(self, return_location):
        """Sets the return_location of this OutboundCapability.


        :param return_location: The return_location of this OutboundCapability.  # noqa: E501
        :type: ReturnLocation
        """

        self._return_location = return_location

    @property
    def delivery_channel(self):
        """Gets the delivery_channel of this OutboundCapability.  # noqa: E501


        :return: The delivery_channel of this OutboundCapability.  # noqa: E501
        :rtype: DeliveryChannel
        """
        return self._delivery_channel

    @delivery_channel.setter
    def delivery_channel(self, delivery_channel):
        """Sets the delivery_channel of this OutboundCapability.


        :param delivery_channel: The delivery_channel of this OutboundCapability.  # noqa: E501
        :type: DeliveryChannel
        """

        self._delivery_channel = delivery_channel

    @property
    def pickup_channel(self):
        """Gets the pickup_channel of this OutboundCapability.  # noqa: E501


        :return: The pickup_channel of this OutboundCapability.  # noqa: E501
        :rtype: PickupChannel
        """
        return self._pickup_channel

    @pickup_channel.setter
    def pickup_channel(self, pickup_channel):
        """Sets the pickup_channel of this OutboundCapability.


        :param pickup_channel: The pickup_channel of this OutboundCapability.  # noqa: E501
        :type: PickupChannel
        """

        self._pickup_channel = pickup_channel

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OutboundCapability, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OutboundCapability):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OutboundCapability):
            return True

        return self.to_dict() != other.to_dict()
