
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-09-08T15:35:01+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "d62109f1f9876c597dc6e8b48f78df4177c1dcb4",
 "version": "3.0.5.post0.dev7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
