
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-09-10T16:44:25+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8902e81ede9e8b3cdba6d644c30ab3c5210c5e8",
 "version": "2025.09.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
