# Generated by Django 5.1.3 on 2025-06-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0053_experiment_experimentstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentfieldvalue',
            name='field_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='instagram.experimentfielddefinition'),
        ),
    ]
