# Generated by Django 4.2.9 on 2024-03-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0004_scout_code_scout_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='city',
            field=models.CharField(default='Nairobi', max_length=20),
            preserve_default=False,
        ),
    ]
