# Generated by Django 4.2.9 on 2024-05-02 07:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0021_instagramuser_qualified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplehttpoperatormodel',
            name='url',
        ),
        migrations.AddField(
            model_name='simplehttpoperatormodel',
            name='urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
