# Generated by Django 4.2.9 on 2024-08-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0026_instagramuser_is_manually_triggered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramuser',
            name='attached_salesrep',
        ),
    ]
