# Generated by Django 4.2.23 on 2025-07-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milalliancetaxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
