# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ClientService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ClientService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x43lientService.proto\x12\x0bgrpc_client\"\x1b\n\x19GenerateNewSessionRequest\"0\n\x1aGenerateNewSessionResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\'\n\x11\x45ndSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\x14\n\x12\x45ndSessionResponse\".\n\x13\x43heckVersionRequest\x12\x17\n\x0flibrary_version\x18\x01 \x01(\t\"J\n\x14\x43heckVersionResponse\x12\x19\n\x11\x64o_versions_match\x18\x01 \x01(\x08\x12\x17\n\x0fmodeler_version\x18\x02 \x01(\t2\xa0\x02\n\rClientService\x12g\n\x12GenerateNewSession\x12&.grpc_client.GenerateNewSessionRequest\x1a\'.grpc_client.GenerateNewSessionResponse\"\x00\x12O\n\nEndSession\x12\x1e.grpc_client.EndSessionRequest\x1a\x1f.grpc_client.EndSessionResponse\"\x00\x12U\n\x0c\x43heckVersion\x12 .grpc_client.CheckVersionRequest\x1a!.grpc_client.CheckVersionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ClientService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATENEWSESSIONREQUEST']._serialized_start=36
  _globals['_GENERATENEWSESSIONREQUEST']._serialized_end=63
  _globals['_GENERATENEWSESSIONRESPONSE']._serialized_start=65
  _globals['_GENERATENEWSESSIONRESPONSE']._serialized_end=113
  _globals['_ENDSESSIONREQUEST']._serialized_start=115
  _globals['_ENDSESSIONREQUEST']._serialized_end=154
  _globals['_ENDSESSIONRESPONSE']._serialized_start=156
  _globals['_ENDSESSIONRESPONSE']._serialized_end=176
  _globals['_CHECKVERSIONREQUEST']._serialized_start=178
  _globals['_CHECKVERSIONREQUEST']._serialized_end=224
  _globals['_CHECKVERSIONRESPONSE']._serialized_start=226
  _globals['_CHECKVERSIONRESPONSE']._serialized_end=300
  _globals['_CLIENTSERVICE']._serialized_start=303
  _globals['_CLIENTSERVICE']._serialized_end=591
# @@protoc_insertion_point(module_scope)
