
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-09-09T16:36:46+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "b94d69fd4a8a72f93016676264fed17aeb744c74",
 "version": "2.5.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
