# coding: utf-8

# flake8: noqa

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "CategoryControllerApi",
    "FewshotControllerApi",
    "ModelControllerApi",
    "PromptControllerApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "FewshotPairRequestDto",
    "FewshotRequestDto",
    "ModelRequestDto",
    "PromptContentRequestDto",
    "PromptRequestDto",
    "PromptVariableRequestDto",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from openapi_client.api.category_controller_api import CategoryControllerApi as CategoryControllerApi
    from openapi_client.api.fewshot_controller_api import FewshotControllerApi as FewshotControllerApi
    from openapi_client.api.model_controller_api import ModelControllerApi as ModelControllerApi
    from openapi_client.api.prompt_controller_api import PromptControllerApi as PromptControllerApi
    
    # import ApiClient
    from openapi_client.api_response import ApiResponse as ApiResponse
    from openapi_client.api_client import ApiClient as ApiClient
    from openapi_client.configuration import Configuration as Configuration
    from openapi_client.exceptions import OpenApiException as OpenApiException
    from openapi_client.exceptions import ApiTypeError as ApiTypeError
    from openapi_client.exceptions import ApiValueError as ApiValueError
    from openapi_client.exceptions import ApiKeyError as ApiKeyError
    from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
    from openapi_client.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from openapi_client.models.fewshot_pair_request_dto import FewshotPairRequestDto as FewshotPairRequestDto
    from openapi_client.models.fewshot_request_dto import FewshotRequestDto as FewshotRequestDto
    from openapi_client.models.model_request_dto import ModelRequestDto as ModelRequestDto
    from openapi_client.models.prompt_content_request_dto import PromptContentRequestDto as PromptContentRequestDto
    from openapi_client.models.prompt_request_dto import PromptRequestDto as PromptRequestDto
    from openapi_client.models.prompt_variable_request_dto import PromptVariableRequestDto as PromptVariableRequestDto
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from openapi_client.api.category_controller_api import CategoryControllerApi as CategoryControllerApi
from openapi_client.api.fewshot_controller_api import FewshotControllerApi as FewshotControllerApi
from openapi_client.api.model_controller_api import ModelControllerApi as ModelControllerApi
from openapi_client.api.prompt_controller_api import PromptControllerApi as PromptControllerApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.fewshot_pair_request_dto import FewshotPairRequestDto as FewshotPairRequestDto
from openapi_client.models.fewshot_request_dto import FewshotRequestDto as FewshotRequestDto
from openapi_client.models.model_request_dto import ModelRequestDto as ModelRequestDto
from openapi_client.models.prompt_content_request_dto import PromptContentRequestDto as PromptContentRequestDto
from openapi_client.models.prompt_request_dto import PromptRequestDto as PromptRequestDto
from openapi_client.models.prompt_variable_request_dto import PromptVariableRequestDto as PromptVariableRequestDto

""",
            name=__name__,
            doc=__doc__,
        )
    )
