from collections.abc import Hashable
from typing import Final, overload

__all__ = ['SBool', 'TRUTH', 'LIE']

class SBool(int):
    @overload
    def __new__(cls) -> SBool: ...
    @overload
    def __new__(cls, witness: object) -> SBool: ...
    def __init__(self, witness: object = False, flavor: Hashable = ...) -> None: ...
    def __invert__(self) -> SBool: ...
    def __and__(self, other: int) -> int: ...
    def __or__(self, other: int) -> int: ...
    def __xor__(self, other: int) -> int: ...

TRUTH: Final[SBool]
LIE: Final[SBool]
