"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/pydub.ipynb.

# %% auto 0
__all__ = ['get_audio_segment']

# %% ../nbs/pydub.ipynb 3
from pydub import AudioSegment

# %% ../nbs/pydub.ipynb 4
def get_audio_segment(
    audio: AudioSegment,  # TODO: Add description
    start: float,  # TODO: Add description
    end: float,  # TODO: Add description
    offset: float=0  # TODO: Add description
) -> AudioSegment:  # TODO: Add return description
    """Extract audio segment between start and end times"""
    start_ms = max(int(start*1000-offset), 0)
    end_ms = min(int(end*1000+offset), len(audio)*1000)
    # print(start_ms/1000, end_ms/1000)
    return audio[start_ms:end_ms]
