SET NOCOUNT ON;

IF OBJECT_ID('tempdb.dbo.#PAT_ID', 'U') IS NOT NULL
DROP TABLE #PAT_ID;

DECLARE @PAT_ID TABLE
(
    PAT_ID NVARCHAR(15)
)

{{ PAT_ID }}

SELECT *
INTO #PAT_ID
FROM @PAT_ID;

SELECT pat.PAT_MRN_ID as MRN
        ,PID.PAT_ID

FROM #PAT_ID PID
JOIN PATIENT pat
ON pat.PAT_ID 
 =PID.PAT_ID
JOIN PATIENT_3 pat3
ON pat.PAT_ID 
 = pat3.PAT_ID
AND pat3.IS_TEST_PAT_YN = 'N'