# Generated by Django 4.2.23 on 2025-07-26 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can view the taxes'), ('admin_access', 'Admin access')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CorpCeo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_updated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaxLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation_id', models.BigIntegerField()),
                ('alliance_id', models.BigIntegerField()),
                ('journal_reference_id', models.BigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('taxed_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ref_type', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('generated_by', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='milalliance_date_a03c65_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='taxledger',
            constraint=models.UniqueConstraint(fields=('corporation_id', 'journal_reference_id'), name='pk_taxledger'),
        ),
        migrations.AddField(
            model_name='corpceo',
            name='corporation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milalliancetaxes.corporation'),
        ),
        migrations.AddField(
            model_name='corpceo',
            name='eve_character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='milalliancetaxes_corpceo', to='eveonline.evecharacter'),
        ),
    ]
