__title__ = """cms_nbi_client"""
__description__ = """Modern async Python client for Calix Management System NBI with full HTTPS support, connection pooling, circuit breakers, and structured logging"""
__url__ = """https://github.com/somenetworking/CMS-NBI-Client"""
__version__ = """2.0.0"""
__author__ = """somenetworking"""
__author_email__ = """andrewshea06@gmail.com"""
__license__ = """GPL-3.0"""