from _typeshed import Incomplete

EXTENSIONS: Incomplete

def extension_available(ext_base_name, verbose: bool = False): ...
def gpu_available(ext_base_name, verbose: bool = False): ...
def mpi_built(verbose: bool = False): ...
def nccl_built(verbose: bool = False): ...
