"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .route_create_request import RouteCreateRequest, RouteCreateRequestTypedDict
from mollie.types import BaseModel
from mollie.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PaymentCreateRouteRequestTypedDict(TypedDict):
    payment_id: str
    r"""Provide the ID of the related payment."""
    route_create_request: NotRequired[RouteCreateRequestTypedDict]


class PaymentCreateRouteRequest(BaseModel):
    payment_id: Annotated[
        str,
        pydantic.Field(alias="paymentId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Provide the ID of the related payment."""

    route_create_request: Annotated[
        Optional[RouteCreateRequest],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
