_K='User who shared the object'
_J='User to be notified'
_I='Date answered'
_H='User who generated the key'
_G='Last update indicator'
_F='Date seen'
_E='Date creation'
_D='Last update'
_C='Date created'
_B=False
_A=True
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework import serializers
class AppVersioning(models.Model):last_available_version_pip=models.CharField(max_length=10,null=_A);last_check_date=models.DateTimeField(null=_A,verbose_name=_C)
class SpartaQubeCode(models.Model):spartaqube_code=models.CharField(max_length=100,default='admin');date_created=models.DateTimeField(null=_A,verbose_name=_C);last_update=models.DateTimeField(null=_A,verbose_name=_D)
class LocalApp(models.Model):app_id=models.CharField(max_length=100);date_created=models.DateTimeField(null=_A,verbose_name=_C)
class Avatar(models.Model):avatar=models.ImageField(null=_A,blank=_A,upload_to='avatars/');image64=models.TextField(null=_A);date_created=models.DateTimeField(null=_A,verbose_name=_C)
class Infrastructure(models.Model):is_cloud=models.BooleanField(default=_A);cloud_provider=models.IntegerField(default=0)
class Company(models.Model):company_name=models.CharField(max_length=256);base_email=models.CharField(max_length=50);domain=models.CharField(max_length=50);email=models.CharField(max_length=50,null=_A);phone=models.CharField(max_length=20,null=_A);industry=models.CharField(max_length=50,null=_A);country=models.CharField(max_length=50,null=_A);city=models.CharField(max_length=50,null=_A);address=models.CharField(max_length=100,null=_A);cto=models.CharField(max_length=50,null=_A);image64=models.TextField(null=_A);main_contact=models.CharField(max_length=50,null=_A,verbose_name='The person which is our main contact in the company to manage the client relationship');date_created=models.DateTimeField(null=_A,verbose_name=_E);is_delete=models.BooleanField(default=_B);is_activate=models.BooleanField(default=_A);number_available_license_business=models.IntegerField(default=1);number_available_license_dev=models.IntegerField(default=0);number_available_license_admin=models.IntegerField(default=0);has_guest_code=models.BooleanField(default=_A);infrastructure=models.OneToOneField(Infrastructure,null=_A,on_delete=models.CASCADE)
class UserProfile(models.Model):
	user=models.OneToOneField(User,on_delete=models.CASCADE);user_profile_id=models.CharField(max_length=100);registration_token=models.CharField(max_length=100);email=models.CharField(max_length=100);avatar=models.ForeignKey(Avatar,null=_A,on_delete=models.CASCADE);company=models.ForeignKey(Company,null=_A,on_delete=models.CASCADE);is_account_validated=models.BooleanField(default=_B);is_banned=models.BooleanField(default=_B);token_reset_password=models.CharField(max_length=100);job_title=models.CharField(max_length=200);job_area=models.IntegerField(default=0);job_status=models.IntegerField(default=0);editor_theme=models.CharField(max_length=100);font_size=models.FloatField(default=13.4);api_key=models.CharField(max_length=100,default='spartaqube_api_key');api_key_ai_plan=models.CharField(max_length=100,default='api_key_ai_plan');is_dark_theme=models.BooleanField(default=_B);is_size_reduced_plot_db=models.BooleanField(default=_B);is_size_reduced_api=models.BooleanField(default=_B);has_open_tickets=models.BooleanField(default=_B);b_created_website=models.BooleanField(default=_B)
	def __str__(A):return'Profile of {0}'.format(A.user.username)
class LoginLocation(models.Model):user=models.ForeignKey(User,on_delete=models.CASCADE);ip=models.CharField(max_length=10);hostname=models.CharField(max_length=10);lat=models.CharField(max_length=10,null=_A);lng=models.CharField(max_length=10,null=_A);country=models.CharField(max_length=10,null=_A);date_login=models.DateTimeField(null=_A,verbose_name=_C)
class ApiToken(models.Model):user=models.OneToOneField(User,on_delete=models.CASCADE);token=models.CharField(max_length=100);date_created=models.DateTimeField(null=_A,verbose_name=_C)
class LLMSettings(models.Model):user=models.ForeignKey(User,on_delete=models.CASCADE);is_autorun=models.BooleanField(default=_B);cloud_model=models.CharField(max_length=100,null=_A,default='gpt-3.5 turbo');last_update=models.DateTimeField(null=_A,verbose_name=_D);date_created=models.DateTimeField(null=_A,verbose_name=_C)
class LLMCredentials(models.Model):user=models.ForeignKey(User,on_delete=models.CASCADE);openai_key=models.CharField(max_length=100,null=_A);anthropic_key=models.CharField(max_length=100,null=_A);gemini_key=models.CharField(max_length=100,null=_A);last_update=models.DateTimeField(null=_A,verbose_name=_D);date_created=models.DateTimeField(null=_A,verbose_name=_C)
class LLMTrialKey(models.Model):is_dev=models.BooleanField(default=_B);user=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name=_H);trial_key=models.CharField(max_length=100,null=_A);last_update=models.DateTimeField(null=_A,verbose_name=_D);date_created=models.DateTimeField(null=_A,verbose_name=_C)
class AIPlan(models.Model):is_dev=models.BooleanField(default=_B);user=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name=_H);api_key_ai_plan=models.CharField(max_length=100,null=_A);existing_api_key_ai_plan=models.CharField(max_length=100,null=_A);reset_api_key_ai_plan=models.CharField(max_length=100,null=_A);personal_openai_key=models.CharField(max_length=100,null=_A,verbose_name='Personal API key to use AI');b_use_personal_key=models.BooleanField(default=_B);is_api_plan_verified=models.BooleanField(default=_B);last_update=models.DateTimeField(null=_A,verbose_name=_D);date_created=models.DateTimeField(null=_A,verbose_name=_C)
class AIPlanSubscription(models.Model):ai_plan=models.ForeignKey(AIPlan,on_delete=models.CASCADE);subscription_key=models.CharField(max_length=100,null=_A);billed_frequency=models.CharField(max_length=20,default='monthly');status=models.CharField(max_length=10,default='pending');last_update=models.DateTimeField(null=_A,verbose_name=_D);date_created=models.DateTimeField(null=_A,verbose_name=_C)
class CloudPlan(models.Model):is_dev=models.BooleanField(default=_B);user=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='User who registered the cloud server');cloud_key=models.CharField(max_length=100);subscription_id=models.CharField(max_length=100,null=_A);ipv4=models.CharField(max_length=40,null=_A);is_verified=models.BooleanField(default=_B);is_destroyed=models.BooleanField(default=_B);date_created=models.DateTimeField(null=_A,verbose_name=_C)
class LLMPort(models.Model):port=models.IntegerField(default=47832);host=models.CharField(max_length=100,null=_A);last_update=models.DateTimeField(null=_A,verbose_name=_C)
class LocalPort(models.Model):port=models.IntegerField(default=8664);last_update=models.DateTimeField(null=_A,verbose_name=_C)
class GuestCode(models.Model):guest_id=models.CharField(max_length=100);date_created=models.DateTimeField(null=_A,verbose_name=_C);is_used=models.BooleanField(default=_B);user=models.ForeignKey(User,null=_A,on_delete=models.CASCADE)
class GuestCodeGlobal(models.Model):guest_id=models.CharField(max_length=100);is_active=models.BooleanField(default=_A);date_created=models.DateTimeField(null=_A,verbose_name=_C)
class UserGroup(models.Model):name=models.CharField(max_length=100);group_id=models.CharField(max_length=100);user_creator=models.ForeignKey(User,on_delete=models.CASCADE);description=models.CharField(max_length=512);avatar=models.ForeignKey(Avatar,null=_A,on_delete=models.CASCADE);is_delete=models.BooleanField(default=_B);date_created=models.DateTimeField(null=_A,verbose_name=_C);last_update=models.DateTimeField(null=_A,verbose_name=_G)
class UserGroupUser(models.Model):user_group=models.ForeignKey(UserGroup,on_delete=models.CASCADE);group_user_id=models.CharField(max_length=100);user=models.ForeignKey(User,on_delete=models.CASCADE);b_admin=models.BooleanField(default=_B);date_created=models.DateTimeField(null=_A,verbose_name=_C);last_update=models.DateTimeField(null=_A,verbose_name=_G);is_delete=models.BooleanField(default=_B)
class ShareRights(models.Model):is_admin=models.BooleanField(default=_A);has_write_rights=models.BooleanField(default=_A);has_reshare_rights=models.BooleanField(default=_A);is_delete=models.BooleanField(default=_A);last_update=models.DateTimeField(null=_A,verbose_name=_G)
class contactUS(models.Model):message=models.TextField(null=_B);title=models.TextField(null=_B);user=models.ForeignKey(User,on_delete=models.CASCADE);is_delete=models.BooleanField(default=_B);date_created=models.DateTimeField(null=_A,verbose_name=_C);has_admin_answered=models.BooleanField(default=_B);date_answered=models.DateTimeField(null=_A,verbose_name=_I);has_user_seen=models.BooleanField(default=_B)
class ticket(models.Model):ticket_id=models.CharField(max_length=100);type_ticket=models.IntegerField(default=1);title=models.TextField(null=_B);is_delete=models.BooleanField(default=_B);has_user_closed=models.BooleanField(default=_B);date_created=models.DateTimeField(null=_A,verbose_name=_C);user=models.ForeignKey(User,on_delete=models.CASCADE);status_ticket=models.IntegerField(default=1);b_send_email=models.BooleanField(default=_B);b_show_user_notification=models.BooleanField(default=_B);has_seen=models.BooleanField(default=_B);last_date_seen=models.DateTimeField(null=_A,verbose_name=_F)
class ticketMessage(models.Model):ticket=models.ForeignKey(ticket,on_delete=models.CASCADE);message=models.TextField(null=_B);user=models.ForeignKey(User,on_delete=models.CASCADE);date_created=models.DateTimeField(null=_A,verbose_name=_C)
class ticketAnswer(models.Model):ticket_message=models.ForeignKey(ticketMessage,on_delete=models.CASCADE);answer=models.TextField(null=_B);user=models.ForeignKey(User,on_delete=models.CASCADE);date_answered=models.DateTimeField(null=_A,verbose_name=_I)
class notifications(models.Model):type_notification=models.IntegerField();message=models.TextField(null=_B);is_seen=models.BooleanField(default=_B);is_delete=models.BooleanField(default=_B);date_created=models.DateTimeField(null=_A,verbose_name=_E);date_seen=models.DateTimeField(null=_A,verbose_name=_F)
class notificationShare(models.Model):user=models.ForeignKey(User,null=_A,on_delete=models.CASCADE,verbose_name=_J);user_group=models.ForeignKey(UserGroup,null=_A,on_delete=models.CASCADE,verbose_name='Group to share the customFunction with');user_from=models.ForeignKey(User,null=_A,related_name='userFromNotificationShare',on_delete=models.CASCADE,verbose_name=_K);type_object=models.IntegerField();is_seen=models.BooleanField(default=_B);is_delete=models.BooleanField(default=_B);date_created=models.DateTimeField(null=_A,verbose_name=_E);date_seen=models.DateTimeField(null=_A,verbose_name=_F)
class notificationGroup(models.Model):user=models.ForeignKey(User,null=_A,on_delete=models.CASCADE,verbose_name=_J);user_from=models.ForeignKey(User,null=_A,related_name='userFromNotificationGroup',on_delete=models.CASCADE,verbose_name=_K);is_seen=models.BooleanField(default=_B);is_delete=models.BooleanField(default=_B);date_created=models.DateTimeField(null=_A,verbose_name=_E);date_seen=models.DateTimeField(null=_A,verbose_name=_F)