_I='Data source configuration'
_H='0.0.1'
_G='Last date used'
_F='Group to share the indicator with'
_E='User to share the indicator with'
_D='Last update'
_C='Date created'
_B=False
_A=True
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework import serializers
from picklefield.fields import PickledObjectField
from project.models_base import ShareRights,UserGroup
class DBConnector(models.Model):connector_id=models.CharField(max_length=100,null=_A);host=models.CharField(max_length=100,null=_A);port=models.CharField(max_length=10,null=_A);user=models.CharField(max_length=100,null=_A);password_e=models.CharField(max_length=100,null=_A);database=models.CharField(max_length=100,null=_A);oracle_service_name=models.CharField(max_length=100,null=_A);keyspace=models.CharField(max_length=100,null=_A);library_arctic=models.CharField(max_length=100,null=_A);database_path=models.CharField(max_length=100,null=_A);csv_path=models.CharField(max_length=100,null=_A);csv_delimiter=models.CharField(max_length=100,null=_A);read_only=models.BooleanField(max_length=100,null=_A,default=_B);json_url=models.CharField(max_length=100,null=_A);socket_url=models.CharField(max_length=100,null=_A);redis_db=models.IntegerField(default=0);token=models.CharField(max_length=100,null=_A);organization=models.CharField(max_length=100,null=_A);lib_dir=models.CharField(max_length=100,null=_A);driver=models.CharField(max_length=100,null=_A);trusted_connection=models.BooleanField(default=_A);dynamic_inputs=models.TextField(null=_A);py_code_processing=models.TextField(null=_A);db_engine=models.CharField(max_length=100,null=_A);name=models.CharField(max_length=100,null=_A);description=models.TextField(null=_A);is_delete=models.BooleanField(default=_B);date_created=models.DateTimeField(null=_A,verbose_name='Date creation');last_update=models.DateTimeField(null=_A,verbose_name=_D);last_date_used=models.DateTimeField(null=_A,verbose_name=_G)
class DBConnectorUserShared(models.Model):db_connector=models.ForeignKey(DBConnector,on_delete=models.CASCADE);user=models.ForeignKey(User,null=_A,on_delete=models.CASCADE,verbose_name=_E);user_group=models.ForeignKey(UserGroup,null=_A,on_delete=models.CASCADE,verbose_name=_F);date_created=models.DateTimeField(null=_A,verbose_name=_C);is_delete=models.BooleanField(default=_B);share_rights=models.ForeignKey(ShareRights,null=_A,on_delete=models.CASCADE);is_owner=models.BooleanField(default=_B)
class CodeEditorNotebook(models.Model):notebook_id=models.CharField(max_length=100,null=_A);name=models.CharField(max_length=100,null=_A);cells=models.TextField(null=_A);is_delete=models.BooleanField(default=_B);date_created=models.DateTimeField(null=_A,verbose_name=_C);last_update=models.DateTimeField(null=_A,verbose_name=_D)
class PlotDBChart(models.Model):plot_chart_id=models.CharField(max_length=100,null=_A);type_chart=models.CharField(max_length=100,null=_A);name=models.CharField(max_length=100,null=_A);slug=models.SlugField(unique=_A,max_length=150,null=_A);description=models.CharField(max_length=1000,null=_A);is_expose_widget=models.BooleanField(default=_B);is_public_widget=models.BooleanField(default=_B);is_static_data=models.BooleanField(default=_B);has_widget_password=models.BooleanField(default=_B);widget_password_e=models.CharField(max_length=100,null=_A);data_source_list=PickledObjectField(default=dict,null=_A,editable=_A,verbose_name=_I);chart_params=PickledObjectField(default=dict,null=_A,editable=_A,verbose_name='This is all the params (type, options, data for chartJS for instance)');chart_config=PickledObjectField(default=dict,null=_A,editable=_A,verbose_name=_I);state_params=PickledObjectField(default=dict,null=_A,editable=_A,verbose_name='This is a dictionary containing the state of the component');is_created_from_api=models.BooleanField(default=_B);is_created_from_dataframe=models.BooleanField(default=_B);thumbnail_path=models.CharField(max_length=100,null=_A);is_delete=models.BooleanField(default=_B);date_created=models.DateTimeField(null=_A,verbose_name=_C);last_update=models.DateTimeField(null=_A,verbose_name=_D);code_editor_notebook=models.ForeignKey(CodeEditorNotebook,null=_A,on_delete=models.CASCADE);last_date_used=models.DateTimeField(null=_A,verbose_name=_G);spartaqube_version=models.CharField(max_length=10,null=_A,default=_H)
class PlotDBChartShared(models.Model):plot_db_chart=models.ForeignKey(PlotDBChart,on_delete=models.CASCADE);user=models.ForeignKey(User,null=_A,on_delete=models.CASCADE,verbose_name=_E);user_group=models.ForeignKey(UserGroup,null=_A,on_delete=models.CASCADE,verbose_name=_F);date_created=models.DateTimeField(null=_A,verbose_name=_C);is_delete=models.BooleanField(default=_B);share_rights=models.ForeignKey(ShareRights,null=_A,on_delete=models.CASCADE);is_owner=models.BooleanField(default=_B)
class PlotDBPermission(models.Model):plot_db_chart=models.ForeignKey(PlotDBChart,on_delete=models.CASCADE);token=models.CharField(max_length=100,null=_A);is_delete=models.BooleanField(default=_B);date_created=models.DateTimeField(null=_A,verbose_name=_C)
class NewPlotApiVariables(models.Model):user=models.ForeignKey(User,null=_A,on_delete=models.CASCADE,verbose_name=_E);pickled_variables=models.TextField(null=_A);session_id=models.CharField(max_length=100,null=_A);is_delete=models.BooleanField(default=_B);date_created=models.DateTimeField(null=_A,verbose_name=_C);last_update=models.DateTimeField(null=_A,verbose_name=_D)
class PaletteColors(models.Model):palette_id=models.CharField(max_length=100,null=_A);user=models.ForeignKey(User,null=_A,on_delete=models.CASCADE,verbose_name=_E);name=models.CharField(max_length=100,null=_A);palette=PickledObjectField(default=dict,null=_A,editable=_A,verbose_name='Palette color');is_default=models.BooleanField(default=_B);is_delete=models.BooleanField(default=_B);date_created=models.DateTimeField(null=_A,verbose_name=_C);last_update=models.DateTimeField(null=_A,verbose_name=_D)
class Dashboard(models.Model):dashboard_id=models.CharField(max_length=100,null=_A);name=models.CharField(max_length=100,null=_A);slug=models.SlugField(unique=_A,max_length=150,null=_A);description=models.CharField(max_length=1000,null=_A);is_expose_dashboard=models.BooleanField(default=_B);is_public_dashboard=models.BooleanField(default=_B);has_password=models.BooleanField(default=_B);password_e=models.CharField(max_length=100,null=_A);is_delete=models.BooleanField(default=_B);dashboard_notebook=models.TextField(null=_A);project_path=models.TextField(null=_A);main_ipynb_fullpath=models.TextField(null=_A);dashboard_venv=models.TextField(null=_A);lumino_layout=models.TextField(null=_A);grid_config=models.TextField(null=_A);plot_db_programmatic_attributes=models.TextField(null=_A);plot_db_dependencies=models.TextField(null=_A);thumbnail_path=models.CharField(max_length=100,null=_A);date_created=models.DateTimeField(null=_A,verbose_name=_C);last_update=models.DateTimeField(null=_A,verbose_name=_D);last_date_used=models.DateTimeField(null=_A,verbose_name=_G);spartaqube_version=models.CharField(max_length=10,null=_A,default=_H)
class DashboardShared(models.Model):dashboard=models.ForeignKey(Dashboard,on_delete=models.CASCADE);user=models.ForeignKey(User,null=_A,on_delete=models.CASCADE,verbose_name=_E);user_group=models.ForeignKey(UserGroup,null=_A,on_delete=models.CASCADE,verbose_name=_F);date_created=models.DateTimeField(null=_A,verbose_name=_C);is_delete=models.BooleanField(default=_B);share_rights=models.ForeignKey(ShareRights,null=_A,on_delete=models.CASCADE);is_owner=models.BooleanField(default=_B)
class Developer(models.Model):is_plot_db=models.BooleanField(default=_A);is_saved_confirmed=models.BooleanField(default=_B);developer_id=models.CharField(max_length=100,null=_A);name=models.CharField(max_length=100,null=_A);slug=models.SlugField(unique=_A,max_length=150,null=_A);description=models.CharField(max_length=1000,null=_A);is_expose_developer=models.BooleanField(default=_B);is_public_developer=models.BooleanField(default=_B);has_password=models.BooleanField(default=_B);password_e=models.CharField(max_length=100,null=_A);is_delete=models.BooleanField(default=_B);project_path=models.TextField(null=_A);developer_venv=models.TextField(null=_A);lumino_layout=models.TextField(null=_A);thumbnail_path=models.CharField(max_length=100,null=_A);date_created=models.DateTimeField(null=_A,verbose_name=_C);last_update=models.DateTimeField(null=_A,verbose_name=_D);last_date_used=models.DateTimeField(null=_A,verbose_name=_G);spartaqube_version=models.CharField(max_length=10,null=_A,default=_H)
class DeveloperShared(models.Model):developer=models.ForeignKey(Developer,on_delete=models.CASCADE);user=models.ForeignKey(User,null=_A,on_delete=models.CASCADE,verbose_name=_E);user_group=models.ForeignKey(UserGroup,null=_A,on_delete=models.CASCADE,verbose_name=_F);date_created=models.DateTimeField(null=_A,verbose_name=_C);is_delete=models.BooleanField(default=_B);share_rights=models.ForeignKey(ShareRights,null=_A,on_delete=models.CASCADE);is_owner=models.BooleanField(default=_B)
class Notebook(models.Model):notebook_id=models.CharField(max_length=100,null=_A);name=models.CharField(max_length=100,null=_A);slug=models.SlugField(unique=_A,max_length=150,null=_A);description=models.CharField(max_length=1000,null=_A);is_expose_notebook=models.BooleanField(default=_B);is_public_notebook=models.BooleanField(default=_B);has_password=models.BooleanField(default=_B);password_e=models.CharField(max_length=100,null=_A);is_delete=models.BooleanField(default=_B);project_path=models.TextField(null=_A);main_ipynb_fullpath=models.TextField(null=_A);notebook_venv=models.TextField(null=_A);lumino_layout=models.TextField(null=_A);thumbnail_path=models.CharField(max_length=100,null=_A);is_exec_code_display=models.BooleanField(default=_A);date_created=models.DateTimeField(null=_A,verbose_name=_C);last_update=models.DateTimeField(null=_A,verbose_name=_D);last_date_used=models.DateTimeField(null=_A,verbose_name=_G);spartaqube_version=models.CharField(max_length=10,null=_A,default=_H)
class NotebookShared(models.Model):notebook=models.ForeignKey(Notebook,on_delete=models.CASCADE);user=models.ForeignKey(User,null=_A,on_delete=models.CASCADE,verbose_name=_E);user_group=models.ForeignKey(UserGroup,null=_A,on_delete=models.CASCADE,verbose_name=_F);date_created=models.DateTimeField(null=_A,verbose_name=_C);is_delete=models.BooleanField(default=_B);share_rights=models.ForeignKey(ShareRights,null=_A,on_delete=models.CASCADE);is_owner=models.BooleanField(default=_B)
class KernelZmqPort(models.Model):port=models.IntegerField(default=0);date_created=models.DateTimeField(null=_A,verbose_name=_C);last_update=models.DateTimeField(null=_A,verbose_name=_D);is_delete=models.BooleanField(default=_B)
class KernelProcess(models.Model):kernel_manager_uuid=models.CharField(max_length=100,null=_A);port=models.IntegerField(default=0);pid=models.CharField(max_length=10,null=_A);user=models.ForeignKey(User,null=_A,on_delete=models.CASCADE,verbose_name='User that spawned the kernel process');name=models.CharField(max_length=100,null=_A);type=models.IntegerField(default=1);notebook_exec_id=models.CharField(max_length=100,null=_A);dashboard_exec_id=models.CharField(max_length=100,null=_A);venv_name=models.CharField(max_length=100,null=_A);project_folder=models.CharField(max_length=100,null=_A);date_created=models.DateTimeField(null=_A,verbose_name=_C);last_update=models.DateTimeField(null=_A,verbose_name=_D);is_delete=models.BooleanField(default=_B)
class Kernel(models.Model):kernel_manager_uuid=models.CharField(max_length=100,null=_A);name=models.CharField(max_length=100,null=_A);slug=models.SlugField(unique=_A,max_length=150,null=_A);description=models.CharField(max_length=1000,null=_A);has_password=models.BooleanField(default=_B);password_e=models.CharField(max_length=100,null=_A);is_delete=models.BooleanField(default=_B);project_path=models.TextField(null=_A);lumino_layout=models.TextField(null=_A);kernel_venv=models.TextField(null=_A);is_static_variables=models.BooleanField(default=_B);kernel_size=models.FloatField(default=0);kernel_variables=models.BinaryField(null=_A);thumbnail_path=models.CharField(max_length=100,null=_A);date_created=models.DateTimeField(null=_A,verbose_name=_C);last_update=models.DateTimeField(null=_A,verbose_name=_D);last_date_used=models.DateTimeField(null=_A,verbose_name=_G);spartaqube_version=models.CharField(max_length=10,null=_A,default=_H)
class KernelShared(models.Model):kernel=models.ForeignKey(Kernel,on_delete=models.CASCADE);user=models.ForeignKey(User,null=_A,on_delete=models.CASCADE,verbose_name=_E);user_group=models.ForeignKey(UserGroup,null=_A,on_delete=models.CASCADE,verbose_name=_F);date_created=models.DateTimeField(null=_A,verbose_name=_C);is_delete=models.BooleanField(default=_B);share_rights=models.ForeignKey(ShareRights,null=_A,on_delete=models.CASCADE);is_owner=models.BooleanField(default=_B)
class DataFrameModel(models.Model):table_name=models.CharField(max_length=100,null=_A);slug=models.SlugField(unique=_A,max_length=150,null=_A);description=models.TextField(null=_A);is_expose_widget=models.BooleanField(default=_A);is_public_widget=models.BooleanField(default=_B);has_widget_password=models.BooleanField(default=_B);widget_password_e=models.CharField(max_length=100,null=_A);dataframe_config=models.TextField(null=_A);plot_db_chart=models.ForeignKey(PlotDBChart,on_delete=models.CASCADE,null=_A);date_created=models.DateTimeField(null=_A,verbose_name=_C);last_update=models.DateTimeField(null=_A,verbose_name=_D);is_delete=models.BooleanField(default=_B);is_dataframe_connector=models.BooleanField(default=_B);connector_config=models.TextField(null=_A)
class DataFrameHistory(models.Model):dataframe_model=models.ForeignKey(DataFrameModel,on_delete=models.CASCADE);df_blob=models.BinaryField(null=_A);dispo=models.CharField(max_length=100,null=_A);date_created=models.DateTimeField(null=_A,verbose_name=_C);last_update=models.DateTimeField(null=_A,verbose_name=_D)
class DataFrameShared(models.Model):dataframe_model=models.ForeignKey(DataFrameModel,on_delete=models.CASCADE);user=models.ForeignKey(User,null=_A,on_delete=models.CASCADE,verbose_name=_E);user_group=models.ForeignKey(UserGroup,null=_A,on_delete=models.CASCADE,verbose_name=_F);date_created=models.DateTimeField(null=_A,verbose_name=_C);is_delete=models.BooleanField(default=_B);share_rights=models.ForeignKey(ShareRights,null=_A,on_delete=models.CASCADE);is_owner=models.BooleanField(default=_B)
class DataFramePermission(models.Model):dataframe_model=models.ForeignKey(DataFrameModel,on_delete=models.CASCADE);token=models.CharField(max_length=100,null=_A);is_delete=models.BooleanField(default=_B);date_created=models.DateTimeField(null=_A,verbose_name=_C)
class DataFrameLLM(models.Model):dataframe_llm_id=models.CharField(max_length=100,null=_A);dataframe_model=models.ForeignKey(DataFrameModel,on_delete=models.CASCADE);user=models.ForeignKey(User,null=_A,on_delete=models.CASCADE,verbose_name='User owner');venv=models.TextField(null=_A);initial_prompt=models.TextField(null=_A);self_correcting=models.BooleanField(default=_A);max_retry=models.IntegerField(default=5);llm_one_liner=models.TextField(null=_A);title_override=models.TextField(null=_A);llm_conversation_list_backend=models.TextField(null=_A);llm_conversation_spartaqube_api_rag=models.TextField(null=_A);response_list_frontend=models.TextField(null=_A);kernel_variables=models.BinaryField(null=_A);is_expose=models.BooleanField(default=_B);is_public=models.BooleanField(default=_B);has_password=models.BooleanField(default=_B);password_e=models.CharField(max_length=100,null=_A);date_created=models.DateTimeField(null=_A,verbose_name=_C);last_update=models.DateTimeField(null=_A,verbose_name=_D);is_delete=models.BooleanField(default=_B)