# Copyright 2023 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================

"""Operator labels and args default value."""
from mindspore.common import dtype as mstype

op_args_default_value = {
    "PagedAttention": {"value_cache": None, "block_tables": None, "context_lens": None, "antiquant_scale": None, "antiquant_offset": None, "attn_mask": None, "q_seq_lens": None, "alibi_mask": None, "kv_cache_quant_mode": 'DEFAULT', "mask_mode": 'MASK_DEFAULT', "mla_v_dim": 0},
    "BCEWithLogitsLoss": {"weight": None, "posWeight": None, "reduction": 'mean'},
    "MatMul": {"transpose_a": False, "transpose_b": False},
    "TopPRouter": {"drop_type": 0, "threshold": 0.0, "router_prob": 0.0},
    "BatchNormExt": {"weight": None, "bias": None, "running_mean": None, "runnning_var": None, "training": False, "momentum": 0.1, "epsilon": 1e-5},
    "TriangularSolve": {"upper": True, "transpose": False, "unitriangular": False},
    "InplaceAddmm": {"beta": 1, "alpha": 1},
    "ResizeLinear1DGrad": {"coordinate_transformation_mode": 'align_corners'},
    "AvgPool3DExt": {"stride": None, "padding": 0, "ceil_mode": False, "count_include_pad": True, "divisor_override": None},
    "CrossEntropyLoss": {"weight": None, "reduction": 'mean', "ignore_index": -100, "label_smoothing": 0.0, "lse_square_scale_for_zloss": 0.0, "return_zloss": False},
    "SumExt": {"dim": None, "keepdim": False, "dtype": None},
    "ResizeNearestNeighborV2": {"align_corners": False, "half_pixel_centers": False},
    "CumsumExt": {"dtype": None},
    "Col2ImGrad": {"dilation": 1, "padding": 0, "stride": 1},
    "SplitWithSizeView": {"dim": 0},
    "RotatedIou": {"trans": False, "mode": 0, "is_cross": True, "v_threshold": 0.0, "e_threshold": 0.0},
    "ConvTranspose2D": {"bias": None, "stride": 1, "padding": 0, "output_padding": 0, "groups": 1, "dilation": 1},
    "IDCTN": {"type": 2, "s": None, "axes": None, "norm": None},
    "InplaceClampTensor": {"min": None, "max": None},
    "DivMod": {"rounding_mode": None},
    "RandpermV2": {"seed": 0, "offset": 0, "dtype": mstype.int64},
    "Std": {"dim": None, "correction": 1, "keepdim": False},
    "RingAttentionUpdate": {"actual_seq_qlen": None, "layout": 'SBH'},
    "ApplyCamePart4": {"global_shape": None},
    "LeakyReLUExt": {"negative_slope": 0.01},
    "TraceV2": {"offset": 0, "axis1": 1, "axis2": 0, "dtype": None},
    "NLLLoss": {"reduction": 'mean', "ignore_index": -100},
    "HardtanhGrad": {"min_val": -1, "max_val": 1},
    "CdistGrad": {"p": 2.0},
    "UpsampleNearest3D": {"output_size": None, "scales": None},
    "BatchNormElemt": {"weight": None, "bias": None, "mean": None, "invstd": None, "eps": 1e-5},
    "BinaryCrossEntropy": {"weight": None, "reduction": 'mean'},
    "Cdist": {"p": 2.0},
    "LayerNormV3": {"begin_norm_axis": 1, "begin_params_axis": 1, "epsilon": 1e-7},
    "ArgMaxExt": {"dim": None, "keepdim": False},
    "InplaceDivMods": {"rounding_mode": None},
    "MoeTokenPermuteGrad": {"num_topk": 1, "padded_mode": False},
    "LpNormV2": {"p": 2, "dim": None, "keepdim": False, "epsilon": 1e-12},
    "CumProd": {"exclusive": False, "reverse": False},
    "GroupNormGrad": {"dx_is_require": True, "dgamma_is_require": True, "dbeta_is_require": True},
    "IndexAddExt": {"alpha": 1},
    "BatchNormGradGrad": {"is_training": False, "epsilon": 1e-5, "data_format": 'NCHW'},
    "FFTN": {"s": None, "dim": None, "norm": None},
    "ReduceProd": {"axis": (), "keep_dims": False},
    "CrossEntropyLossGrad": {"weight": None, "grad_zloss": None, "lse_for_zloss": None, "reduction": 'mean', "ignore_index": -100, "label_smoothing": 0.0, "lse_square_scale_for_zloss": 0.0},
    "CeLU": {"alpha": 1.0},
    "ResizeD": {"coordinate_transformation_mode": 'align_corners'},
    "SplitTensorView": {"dim": 0},
    "GroupNorm": {"weight": None, "bias": None, "eps": 1e-5},
    "MatmulReduceScatter": {"reduce_op": 'sum', "bias": None, "comm_turn": 0, "trans_input": False, "trans_x2": False},
    "SilentCheckV2": {"c_min_steps": 7, "c_thresh_l1": 1000000.0, "c_coeff_l1": 100000.0, "c_thresh_l2": 10000.0, "c_coeff_l2": 5000.0, "npu_asd_detect": 1},
    "FillScalar": {"dtype": None},
    "RmsNorm": {"epsilon": 1e-6},
    "L1LossBackwardExt": {"reduction": 'mean'},
    "SmoothL1LossGrad": {"beta": 1.0, "reduction": 'none'},
    "Im2ColExt": {"dilation": 1, "padding": 0, "stride": 1},
    "Mla": {"attn_mask": None, "deq_scale_qk": None, "deq_scale_pv": None, "q_seq_lens": None, "context_lens": None, "head_num": 32, "scale_value": 0.0, "kv_head_num": 1, "mask_mode": 'MASK_NONE', "is_ring": 0},
    "AddcdivExt": {"value": 1},
    "AvgPoolGrad": {"kernel_size": 1, "strides": 1, "pad_mode": 'VALID', "data_format": 'NCHW'},
    "LogSumExp": {"keepdim": False},
    "UpsampleTrilinear3DGrad": {"output_size": None, "scales": None, "align_corners": False},
    "DCT": {"type": 2, "n": None, "axis": -1, "norm": None},
    "BiasAddGrad": {"data_format": 'NCHW'},
    "MaxDim": {"keepdim": False},
    "UpsampleNearest1D": {"output_size": None, "scales": None},
    "CountNonZero": {"dim": None},
    "Dropout": {"keep_prob": 0.5, "Seed0": 0, "Seed1": 0},
    "Softmax": {"axis": -1},
    "LayerNormGradGrad": {"begin_norm_axis": 1, "begin_params_axis": 1},
    "IsClose": {"rtol": 1e-05, "atol": 1e-08, "equal_nan": False},
    "MaximumGradGrad": {"grad_x": True, "grad_y": True},
    "EmbeddingApplyAdamW": {"ams_grad": (0,), "mask_zero": (0,), "padding_key": (0,), "padding_key_mask": (1,), "completion_key": (0,), "completion_key_mask": (1,), "_embedding_dim": 1, "_max_key_num": 1},
    "BatchNormGradWithAddAndActivation": {"is_training": False, "epsilon": 1e-5, "data_format": 'NCHW'},
    "Range": {"maxlen": 1000000},
    "NLLLossGrad": {"reduction": 'mean', "ignore_index": -100},
    "ResizeBicubicGrad": {"align_corners": False, "half_pixel_centers": False},
    "EmptyLike": {"dtype": None, "device": None},
    "Conv3DPadding": {"bias": None, "stride": 1, "padding": 'valid', "dilation": 1, "groups": 1},
    "LayerNormExt": {"weight": None, "bias": None, "eps": 1e-5},
    "FFTShift": {"dim": None},
    "LinSpaceExt": {"dtype": None},
    "LogSoftmaxExt": {"dim": None, "dtype": None},
    "NLLLoss2d": {"reduction": 'mean', "ignore_index": -100},
    "ApplyAdamW": {"max_grad_norm": None, "amsgrad": False, "maximize": False},
    "GLU": {"axis": -1},
    "IRFFT": {"n": None, "dim": -1, "norm": None},
    "IHFFTN": {"s": None, "dim": None, "norm": None},
    "Correlate": {"pad_mode": 'valid'},
    "InplacePut": {"accumulate": False},
    "RFFT": {"n": None, "dim": -1, "norm": None},
    "UpsampleBilinear2D": {"output_size": None, "scales": None, "align_corners": False},
    "Concat": {"axis": 0},
    "ConvolutionStrGrad": {"bias": None, "stride": 1, "padding": 'valid', "dilation": 1, "transposed": False, "output_padding": 0, "groups": 1, "output_mask": ()},
    "KLDivGrad": {"reduction": 'mean', "log_target": False},
    "Kthvalue": {"dim": -1, "keepdim": False},
    "MoeDistributeDispatch": {"expert_scales": None, "scales": None, "x_active_mask": None, "group_ep": None, "group_tp": None, "tp_world_size": 0, "tp_rank_id": 0, "expert_shard_type": 0, "shared_expert_num": 0, "shared_expert_rank_num": 0, "quant_mode": 0, "global_bs": 0, "expert_token_nums_type": 0},
    "InplaceSubExt": {"alpha": 1},
    "Ones": {"dtype": None},
    "Logit": {"eps": -1.0},
    "Baddbmm": {"beta": 1, "alpha": 1},
    "FullLike": {"dtype": None},
    "IncreFlashAttention": {"attn_mask": None, "actual_seq_lengths": None, "pse_shift": None, "dequant_scale1": None, "quant_scale1": None, "dequant_scale2": None, "quant_scale2": None, "quant_offset2": None, "antiquant_scale": None, "antiquant_offset": None, "block_table": None, "kv_padding_size": None, "num_heads": 1, "input_layout": 'BSH', "scale_value": 1.0, "num_key_value_heads": 0, "block_size": 0, "inner_precise": 1},
    "SoftShrink": {"lambd": 0.5},
    "BincountExt": {"weights": None, "minlength": 0},
    "SortExt": {"dim": -1, "descending": False, "stable": False},
    "FFTFreq": {"d": 1.0, "dtype": None},
    "SplitWithSize": {"dim": 0},
    "EmbeddingApplyAdaGrad": {"mask_zero": (0,), "padding_key": (0,), "padding_key_mask": (1,), "completion_key": (0,), "completion_key_mask": (1,), "_embedding_dim": 1, "_max_key_num": 1},
    "BiasAdd": {"data_format": 'NCHW'},
    "EluGradExt": {"alpha": 1.0, "is_result": False},
    "InsertGemV2InBackward": {"start": 0, "steps": 1, "error_mode": 'cycle', "flip_mode": 'bitflip', "multiply_factor": 0.0, "bit_pos": 0, "flip_probability": 0.0},
    "BatchNormGatherStatsWithCounts": {"running_mean": None, "running_var": None, "momentum": 1e-1, "eps": 1e-5, "counts": None},
    "IHFFT2": {"s": None, "dim": (-2, -1), "norm": None},
    "FlashAttentionScore": {"real_shift": None, "drop_mask": None, "padding_mask": None, "attn_mask": None, "prefix": None, "actual_seq_qlen": None, "actual_seq_kvlen": None, "keep_prob": 1.0, "scale_value": 1.0, "pre_tokens": 2147483647, "next_tokens": 2147483647, "inner_precise": 0, "input_layout": 'BSH', "sparse_mode": 0},
    "EluExt": {"alpha": 1.0},
    "DiagonalView": {"offset": 0, "dim1": 0, "dim2": 1},
    "AvgPool": {"kernel_size": 1, "strides": 1, "pad_mode": 'VALID', "data_format": 'NCHW'},
    "MeanExt": {"dim": None, "keepdim": False, "dtype": None},
    "L1LossExt": {"reduction": 'mean'},
    "BinaryCrossEntropyGrad": {"weight": None, "reduction": 'mean'},
    "SoftmaxBackward": {"dim": -1},
    "ResizeBilinearGrad": {"align_corners": False, "half_pixel_centers": False},
    "Conv1DExt": {"bias": None, "stride": 1, "padding": 0, "dilation": 1, "groups": 1},
    "AddRmsNorm": {"epsilon": 1e-6},
    "InplaceClampScalar": {"min": None, "max": None},
    "UpsampleNearest3DGrad": {"output_size": None, "scales": None},
    "PromptFlashAttention": {"attn_mask": None, "actual_seq_lengths": None, "actual_seq_lengths_kv": None, "pse_shift": None, "deq_scale1": None, "quant_scale1": None, "deq_scale2": None, "quant_scale2": None, "quant_offset2": None, "num_heads": 1, "scale_value": 1.0, "pre_tokens": 2147483647, "next_tokens": 0, "input_layout": 'BSH', "num_key_value_heads": 0, "sparse_mode": 0, "inner_precise": 1},
    "RotaryPositionEmbeddingGrad": {"dx": None, "mode": 0},
    "SilentCheckV3": {"c_thresh_l1": 1000000.0, "c_thresh_l2": 10000.0, "beta1": 0.0, "npu_asd_detect": 1},
    "DCTN": {"type": 2, "s": None, "axes": None, "norm": None},
    "DivMods": {"rounding_mode": None},
    "Cross": {"dim": -65530},
    "MlaPreprocess": {"param_cache_mode": 0},
    "GridSampler3DGrad": {"interpolation_mode": 'bilinear', "padding_mode": 'zeros', "align_corners": False, "output_mask": (1, 1)},
    "UpsampleTrilinear3D": {"output_size": None, "scales": None, "align_corners": False},
    "LayerNorm": {"begin_norm_axis": 1, "begin_params_axis": 1, "epsilon": 1e-7},
    "ResizeNearestNeighborGrad": {"align_corners": False, "half_pixel_centers": False},
    "BatchNorm": {"is_training": False, "epsilon": 1e-5, "momentum": 0.1, "data_format": 'NCHW'},
    "SolveTriangular": {"trans": 0, "lower": False, "unit_diagonal": False},
    "Dense": {"bias": None},
    "RandpermExt": {"dtype": mstype.int64},
    "SoftplusExt": {"beta": 1, "threshold": 20},
    "BinaryCrossEntropyWithLogitsBackward": {"weight": None, "posWeight": None, "reduction": 'mean'},
    "ResizeNearestNeighbor": {"align_corners": False, "half_pixel_centers": False},
    "GridSampler3D": {"interpolation_mode": 'bilinear', "padding_mode": 'zeros', "align_corners": False},
    "BatchNormGradWithActivation": {"is_training": False, "epsilon": 1e-5, "data_format": 'NCHW'},
    "SplitTensor": {"dim": 0},
    "FillTensor": {"dtype": None},
    "IRFFTDouble": {"dim": -1},
    "ChunkView": {"dim": 0},
    "GenerateEodMaskV2": {"start": 0, "steps": 1, "error_mode": 'cycle', "flip_mode": 'bitflip', "multiply_factor": 0.0, "bit_pos": 0, "flip_probability": 0.0},
    "SmoothL1Loss": {"beta": 1.0, "reduction": 'none'},
    "RandExt": {"dtype": None},
    "UpsampleLinear1DGrad": {"output_size": None, "scales": None, "align_corners": False},
    "AdamW": {"amsgrad": False, "maximize": False},
    "LinalgQr": {"mode": 'reduced'},
    "EmbeddingApplyAdam": {"mask_zero": (0,), "padding_key": (0,), "padding_key_mask": (1,), "completion_key": (0,), "completion_key_mask": (1,), "_embedding_dim": 1, "_max_key_num": 1},
    "Arange": {"dtype": None},
    "ArgMaxWithValue": {"axis": 0, "keep_dims": False},
    "MaxPoolWithMask": {"strides": None, "pads": 0, "dilation": (1, 1), "ceil_mode": False, "argmax_type": mstype.int64},
    "ReduceAny": {"axis": (), "keep_dims": False},
    "RandnLike": {"dtype": None},
    "RandLikeExt": {"dtype": None},
    "IDCT": {"type": 2, "n": None, "axis": -1, "norm": None},
    "InplaceIndexPut": {"accumulate": False},
    "MoeTokenUnpermuteGrad": {"probs": None, "padded_mode": False, "restore_shape": None},
    "UpsampleNearest2DGrad": {"output_size": None, "scales": None},
    "SearchSorted": {"sorter": None, "dtype": mstype.int64, "right": False},
    "Elu": {"alpha": 1.0},
    "Addbmm": {"beta": 1, "alpha": 1},
    "AvgPool2D": {"padding": 0, "ceil_mode": False, "count_include_pad": True, "divisor_override": None},
    "SequenceConcat": {"axis": 0},
    "InplaceCopy": {"non_blocking": False},
    "Round": {"decimals": 0},
    "Conv1DPadding": {"bias": None, "stride": 1, "padding": 'valid', "dilation": 1, "groups": 1},
    "Chunk": {"dim": 0},
    "MedianDim": {"dim": -1, "keepdim": False},
    "FFT2": {"s": None, "dim": (-2, -1), "norm": None},
    "IRFFTN": {"s": None, "dim": None, "norm": None},
    "StdMean": {"dim": None, "correction": 1, "keepdim": False},
    "EmbeddingFeatureMappingImport": {"only_offset_flag": True, "num": 1},
    "Nansum": {"dim": None, "keepdim": False, "dtype": None},
    "Hardtanh": {"min_val": -1, "max_val": 1},
    "NewOnes": {"dtype": None},
    "UpsampleNearest2D": {"output_size": None, "scales": None},
    "AsStrided": {"storage_offset": 0},
    "ResizeBicubic": {"align_corners": False, "half_pixel_centers": False},
    "SoftplusGradExt": {"beta": 1, "threshold": 20},
    "TopKRouter": {"drop_type": 0},
    "EmbeddingApplySgd": {"mask_zero": (0,), "padding_key": (0,), "padding_key_mask": (1,), "completion_key": (0,), "completion_key_mask": (1,), "_embedding_dim": 1, "_max_key_num": 1},
    "AvgPool3DGradExt": {"stride": None, "padding": 0, "ceil_mode": False, "count_include_pad": True, "divisor_override": None},
    "ClampTensor": {"min": None, "max": None},
    "InplaceFillDiagonal": {"wrap": False},
    "UpsampleLinear1D": {"output_size": None, "scales": None, "align_corners": False},
    "TensorScatterElements": {"axis": 0, "reduce": 'none'},
    "EmbeddingDenseBackward": {"padding_idx": None, "scale_grad_by_freq": False},
    "Swiglu": {"dim": -1},
    "RFFT2": {"s": None, "dim": (-2, -1), "norm": None},
    "HistcExt": {"bins": 100, "min": 0, "max": 0},
    "VarMean": {"dim": None, "correction": 1, "keepdim": False},
    "DiagExt": {"diagonal": 0},
    "UnstackExtView": {"dim": 0},
    "Unique2": {"sorted": True, "return_inverse": False, "return_counts": False},
    "Eig": {"compute_v": False},
    "RandIntLike": {"dtype": None},
    "LinalgVectorNorm": {"ord": 2, "dim": None, "keepdim": False, "dtype": None},
    "GridSampler2D": {"interpolation_mode": 'bilinear', "padding_mode": 'zeros', "align_corners": False},
    "LayerNormGradExt": {"output_mask": (1, 1, 1)},
    "LeakyReLUGradExt": {"negative_slope": 0.01, "is_result": False},
    "Zeros": {"dtype": None},
    "GeluGradExt": {"approximate": 'none'},
    "RFFTN": {"s": None, "dim": None, "norm": None},
    "MinimumGrad": {"grad_x": True, "grad_y": True},
    "IFFT": {"n": None, "dim": -1, "norm": None},
    "MoeDistributeCombine": {"tp_send_counts": None, "x_active_mask": None, "activate_scale": None, "weight_scale": None, "group_list": None, "expand_scales": None, "group_ep": None, "group_tp": None, "tp_world_size": 0, "tp_rank_id": 0, "expert_shard_type": 0, "shared_expert_num": 0, "shared_export_rank_num": 0, "global_bs": 0, "out_dtype": 0, "common_quant_mode": 0, "group_list_type": 0},
    "Norm": {"p": 2.0, "dim": None, "keepdim": False, "dtype": None},
    "NewEmpty": {"dtype": None, "device": None},
    "MaxPoolGradWithMask": {"strides": None, "pads": 0, "dilation": (1, 1), "ceil_mode": False, "argmax_type": mstype.int64},
    "ReduceSum": {"axis": (), "keep_dims": False, "skip_mode": False},
    "HShrinkGrad": {"lambd": 0.5},
    "Addmm": {"beta": 1, "alpha": 1},
    "SpeedFusionAttentionGrad": {"pse": None, "padding_mask": None, "atten_mask": None, "softmax_max": None, "softmax_sum": None, "softmax_in": None, "attention_in": None, "scale_value": 1.0, "keep_prob": 1.0, "pre_tokens": 2147483647, "next_tokens": 2147483647, "inner_precise": 0, "seed": None, "offset": None, "numels": None, "prefix": None, "actual_seq_qlen": None, "actual_seq_kvlen": None, "sparse_mode": 0, "gen_mask_parallel": True, "sync": False, "pse_type": 1, "q_start_idx": None, "kv_start_idx": None},
    "ConvolutionGrad": {"bias": None, "stride": 1, "padding": 0, "dilation": (1, 1), "transposed": False, "output_padding": 0, "groups": 1, "output_mask": ()},
    "MaxPoolWithIndices": {"strides": None, "pads": 0, "dilation": (1, 1), "ceil_mode": False, "argmax_type": mstype.int64},
    "SubScalar": {"alpha": 1},
    "HShrink": {"lambd": 0.5},
    "LayerNormGrad": {"begin_norm_axis": 1, "begin_params_axis": 1},
    "BatchNormWithAddAndActivation": {"is_training": False, "epsilon": 1e-5, "momentum": 0.1, "data_format": 'NCHW'},
    "RFFTFreq": {"d": 1.0, "dtype": None},
    "ReduceMin": {"axis": (), "keep_dims": False},
    "SoftMarginLossGrad": {"reduction": 'mean'},
    "StridedSlice": {"begin_mask": 0, "end_mask": 0, "ellipsis_mask": 0, "new_axis_mask": 0, "shrink_axis_mask": 0},
    "SoftShrinkGrad": {"lambd": 0.5},
    "UniqueConsecutive": {"return_inverse": False, "return_counts": False, "dim": None},
    "Argmin": {"axis": -1, "output_type": mstype.int32},
    "ResizeNearestNeighborV2Grad": {"align_corners": False, "half_pixel_centers": False},
    "NanToNum": {"nan": None, "posinf": None, "neginf": None},
    "UpsampleBilinear2DGrad": {"output_size": None, "scales": None, "align_corners": False},
    "MSELossGradExt": {"reduction": 'mean'},
    "BatchNormGradExt": {"weight": None, "running_mean": None, "running_var": None, "saved_mean": None, "saved_rstd": None, "training": False, "eps": 1e-5, "output_mask": (1, 1, 1)},
    "GeluExt": {"approximate": 'none'},
    "Scatter": {"reduce": 'none'},
    "AddLayerNormV2": {"epsilon": 1e-5, "additionalOut": False},
    "AddcmulExt": {"value": 1},
    "IFFTN": {"s": None, "dim": None, "norm": None},
    "FlashAttentionScoreGrad": {"pse_shift": None, "drop_mask": None, "padding_mask": None, "atten_mask": None, "softmax_max": None, "softmax_sum": None, "softmax_in": None, "attention_in": None, "prefix": None, "actual_seq_qlen": None, "actual_seq_kvlen": None, "keep_prob": 1.0, "scale_value": 1.0, "pre_tokens": 65536, "next_tokens": 65536, "inner_precise": 1, "input_layout": 'BSH', "sparse_mode": 0},
    "ArgSort": {"dim": -1, "descending": False, "stable": False},
    "AvgPool2DGrad": {"padding": 0, "ceil_mode": False, "count_include_pad": True, "divisor_override": None},
    "Embedding": {"padding_idx": None, "max_norm": None, "norm_type": 2.0, "scale_grad_by_freq": False},
    "OneHot": {"axis": -1},
    "LayerNormGradV3": {"begin_norm_axis": 1, "begin_params_axis": 1},
    "EmbeddingFeatureMappingFind": {"num": 1},
    "HFFT2": {"s": None, "dim": (-2, -1), "norm": None},
    "MSELossExt": {"reduction": 'mean'},
    "OneHotExt": {"axis": -1},
    "HFFTN": {"s": None, "dim": None, "norm": None},
    "IFFT2": {"s": None, "dim": (-2, -1), "norm": None},
    "ConvolutionStr": {"bias": None, "stride": 1, "padding": 'valid', "dilation": 1, "transposed": False, "output_padding": 0, "groups": 1},
    "EmbeddingApplyRmsprop": {"mask_zero": (0,), "padding_key": (0,), "padding_key_mask": (1,), "completion_key": (0,), "completion_key_mask": (1,), "_embedding_dim": 1, "_max_key_num": 1},
    "RandInt": {"dtype": None},
    "NewZeros": {"dtype": None},
    "SpeedFusionAttention": {"pse": None, "padding_mask": None, "atten_mask": None, "scale": 1.0, "keep_prob": 1.0, "pre_tokens": 2147483647, "next_tokens": 2147483647, "inner_precise": 0, "prefix": None, "actual_seq_qlen": None, "actual_seq_kvlen": None, "sparse_mode": 0, "gen_mask_parallel": True, "sync": False, "pse_type": 1, "q_start_idx": None, "kv_start_idx": None},
    "CholeskyInverse": {"upper": False},
    "ResizeLinear1D": {"coordinate_transformation_mode": 'align_corners'},
    "InplaceElu": {"alpha": 1.0},
    "LogSoftmax": {"axis": -1},
    "Col2ImExt": {"dilation": 1, "padding": 0, "stride": 1},
    "LogSoftmaxGrad": {"axis": -1},
    "TupleToTensor": {"dtype": None},
    "FFNExt": {"expertTokens": None, "bias1": None, "bias2": None, "scale": None, "offset": None, "deqScale1": None, "deqScale2": None, "antiquant_scale1": None, "antiquant_scale2": None, "antiquant_offset1": None, "antiquant_offset2": None, "activation": 'fastgelu', "inner_precise": 0},
    "ZerosLikeExt": {"dtype": None},
    "Meshgrid": {"indexing": 'xy'},
    "Conv3DExt": {"bias": None, "stride": 1, "padding": 0, "dilation": 1, "groups": 1},
    "InplaceIndexAddExt": {"alpha": 1},
    "ScatterValue": {"reduce": 'none'},
    "IHFFT": {"n": None, "dim": -1, "norm": None},
    "UpsampleNearest1DGrad": {"output_size": None, "scales": None},
    "EmbeddingApplyFtrl": {"mask_zero": (0,), "padding_key": (0,), "padding_key_mask": (1,), "completion_key": (0,), "completion_key_mask": (1,), "_embedding_dim": 1, "_max_key_num": 1},
    "ReduceAll": {"axis": None, "keep_dims": False},
    "Split": {"axis": 0, "output_num": 1},
    "SwigluGrad": {"dim": -1},
    "ReduceStd": {"axis": [], "unbiased": True, "keep_dims": False},
    "LstsqV2": {"driver": None},
    "LogitGrad": {"eps": -1.0},
    "InnerInplaceIndexPut": {"accumulate": False},
    "FFTWithSize": {"norm": 'backward', "onesided": True, "signal_sizes": ()},
    "ResizeBilinearV2": {"align_corners": False, "half_pixel_centers": False},
    "ApplyRotaryPosEmb": {"cos_format": 0},
    "Squeeze": {"axis": ()},
    "Qr": {"full_matrices": False},
    "OnesLikeExt": {"dtype": None},
    "ProdExt": {"dim": None, "keepdim": False, "dtype": None},
    "GroupTopk": {"k_inner": 1},
    "IFFTShift": {"dim": None},
    "IRFFT2": {"s": None, "dim": (-2, -1), "norm": None},
    "CumSum": {"exclusive": False, "reverse": False},
    "FFT": {"n": None, "dim": -1, "norm": None},
    "MaximumGrad": {"grad_x": True, "grad_y": True},
    "Roll": {"dims": None},
    "ApplyCamePart3": {"global_shape": None, "use_first_moment": False},
    "Randn": {"dtype": None},
    "AdamWeightDecay": {"use_locking": False},
    "AvgPool1D": {"stride": None, "padding": 0, "ceil_mode": False, "count_include_pad": True},
    "SubExt": {"alpha": 1},
    "Gather": {"batch_dims": 0},
    "Conv2DExt": {"bias": None, "stride": 1, "padding": 0, "dilation": 1, "groups": 1},
    "InplaceDivMod": {"rounding_mode": None},
    "InnerMoeTokenUnpermute": {"probs": None, "padded_mode": False, "restore_shape": None},
    "ReduceMax": {"axis": (), "keep_dims": False},
    "TraceV2Grad": {"offset": 0, "axis1": 1, "axis2": 0},
    "SoftMarginLoss": {"reduction": 'mean'},
    "AllGatherMatmul": {"bias": None, "gather_index": 0, "gather_output": True, "comm_turn": 0, "trans_input": False, "trans_x2": False},
    "BatchNormGrad": {"is_training": False, "epsilon": 1e-5, "data_format": 'NCHW'},
    "FlattenExt": {"start_dim": 0, "end_dim": -1},
    "FusedAddTopKDiv": {"activate_type": 0, "is_norm": True, "scale": 2.5, "mapping_num": None, "mapping_table": None, "enable_expert_mapping": False},
    "Convolution": {"bias": None, "stride": 1, "padding": 0, "dilation": 1, "transposed": False, "output_padding": 0, "groups": 1},
    "Addmv": {"beta": 1, "alpha": 1},
    "Triu": {"diagonal": 0},
    "InplaceRandom": {"from_": 0, "to": None, "seed": 0, "offset": 0},
    "MaxPoolGradWithIndices": {"strides": None, "pads": 0, "dilation": (1, 1), "ceil_mode": False, "argmax_type": mstype.int64},
    "EmbeddingTableEvict": {"steps_to_live": 0},
    "NewFull": {"dtype": None},
    "ReshapeAndCache": {"value": None, "key_cache": None, "value_cache": None, "slot_mapping": None},
    "RepeatInterleaveTensor": {"dim": None, "output_size": None},
    "Svd": {"full_matrices": False, "compute_uv": True},
    "InplaceHardtanh": {"min_val": -1, "max_val": 1},
    "ExtractImagePatches": {"padding": 'VALID'},
    "Cholesky": {"upper": False},
    "ApplyCamePart2": {"sum_r": None, "global_shape": None},
    "Empty": {"dtype": None, "device": None},
    "GridSampler2DGrad": {"interpolation_mode": 'bilinear', "padding_mode": 'zeros', "align_corners": False, "output_mask": (1, 1)},
    "AddScalar": {"alpha": 1},
    "EmbeddingFeatureMappingFileSize": {"only_offset_flag": True},
    "TopkExt": {"dim": -1, "largest": True, "sorted": True},
    "ClampScalar": {"min": None, "max": None},
    "InplaceSubScalar": {"alpha": 1},
    "Diagonal": {"offset": 0, "dim1": 0, "dim2": 1},
    "ConstantPadND": {"value": 0.0},
    "KLDiv": {"reduction": 'mean', "log_target": False},
    "TrilExt": {"diagonal": 0},
    "InplaceAddsExt": {"alpha": 1},
    "StackExt": {"dim": 0},
    "AddExt": {"alpha": 1},
    "ScalarToTensor": {"dtype": None},
    "FFTOrtho": {"axes": None, "forward": True},
    "UpsampleBicubic2D": {"output_size": None, "scales": None, "align_corners": False},
    "RotaryPositionEmbedding": {"mode": 0},
    "BatchMatMul": {"transpose_a": False, "transpose_b": False},
    "ArgMinExt": {"dim": None, "keepdim": False},
    "Conv2DPadding": {"bias": None, "stride": 1, "padding": 'valid', "dilation": 1, "groups": 1},
    "ArgMinWithValue": {"axis": 0, "keep_dims": False},
    "RepeatInterleaveInt": {"dim": None, "output_size": None},
    "MoeTokenPermute": {"num_out_tokens": None, "padded_mode": False},
    "Argmax": {"axis": -1, "output_type": mstype.int32},
    "HFFT": {"n": None, "dim": -1, "norm": None},
    "InplaceAddExt": {"alpha": 1},
    "MaxUnpool2DExt": {"stride": None, "padding": 0, "output_size": None},
    "UpsampleBicubic2DGrad": {"output_size": None, "scales": None, "align_corners": False},
    "MinDim": {"keepdim": False},
    "PagedAttentionMask": {"antiquant_scale": None, "antiquant_offset": None, "alibi_mask": None, "kv_cache_quant_mode": 'DEFAULT'},
    "BatchNormWithActivation": {"is_training": False, "epsilon": 1e-5, "momentum": 0.1, "data_format": 'NCHW'},
    "Var": {"dim": None, "correction": 1, "keepdim": False},
    "ReduceMean": {"axis": (), "keep_dims": False},
    "MoeFinalizeRouting": {"x2": None, "bias": None, "scales": None, "expanded_row_idx": None, "expanded_expert_idx": None},
    "MoeInitRoutingQuantV2": {"scale": None, "offset": None},
    "KVCacheScatterUpdate": {"reduce": 'none'},
    "DynamicQuantExt": {"smooth_scales": None},
    "AddRmsNormDynamicQuant": {"smooth_scale2": None, "epsilon": 1e-5},
    "SwiGLUDynamicQuant": {"smooth_scale": None},
    "MatmulAllReduceAddRmsNorm": {"reduce_op": 'sum', "comm_turn": 0, "stream_mode": 1},
    "FusedInferAttentionScore": {"pse_shift": None, "attn_mask": None, "actual_seq_lengths": None, "actual_seq_lengths_kv": None, "dequant_scale1": None, "quant_scale1": None, "dequant_scale2": None, "quant_scale2": None, "quant_offset2": None, "antiquant_scale": None, "antiquant_offset": None, "block_table": None, "query_padding_size": None, "kv_padding_size": None, "key_antiquant_scale": None, "key_antiquant_offset": None, "value_antiquant_scale": None, "value_antiquant_offset": None, "key_shared_prefix": None, "value_shared_prefix": None, "actual_shared_prefix_len": None, "num_heads": 1, "scale_value": 1.0, "pre_tokens": 2147483647, "next_tokens": 2147483647, "input_layout": 'BSH', "num_key_value_heads": 0, "sparse_mode": 0, "inner_precise": 1, "block_size": 0, "antiquant_mode": 0, "softmax_lse_flag": False, "key_antiquant_mode": 0, "value_antiquant_mode": 0},
    "QuantBatchMatmul": {"offset": None, "bias": None, "pertokenScaleOptional": None, "transpose_x1": False, "transpose_x2": False, "dtype": mstype.float16},
    "TransposeBatchMatmulTranspose": {"transpose_a": False, "transpose_b": False},
    "RmsNormQuant": {"beta": None, "epsilon": 1e-6},
    "MoeGatingTopKSoftmax": {"finished": None, "k": 1},
    "QuantV2": {"sqrt_mode": False, "rounding_mode": 'ROUND', "dst_type": mstype.int8},
    "AddRmsNormQuantV2": {"epsilon": 1e-5},
    "DynamicNTK": {"dtype": mstype.float16},
    "WeightQuantBatchMatmul": {"antiquant_offset": None, "quant_scale": None, "quant_offset": None, "bias": None, "transpose_x": False, "transpose_weight": False, "antiquant_group_size": 0},
    "QuantMatmul": {"offset": None, "pertoken_scale": None, "bias": None, "output_dtype": None, "x1_dtype": None, "x2_dtype": None, "pertoken_scale_dtype": None, "scale_dtype": None, "group_sizes": None},
    "GroupedMatmulV4": {"bias": None, "scale": None, "offset": None, "antiquant_scale": None, "antiquant_offset": None, "pre_token_scale": None, "group_list": None, "activation_input": None, "activation_quant_scale": None, "activation_quant_offset": None, "split_item": 0, "group_type": -1, "group_list_type": 0, "act_type": 0},
    "GroupedMatmulV2": {"bias": None, "scale": None, "offset": None, "antiquant_scale": None, "antiquant_offset": None, "group_list": None, "split_item": 0, "group_type": -1},
    "GroupedMatmul": {"bias": None, "scale": None, "offset": None, "antiquant_scale": None, "antiquant_offset": None, "group_list": None, "split_item": 0, "group_type": -1, "transpose_a": False, "transpose_b": False},
    "GmmBackward": {"group_list": None, "group_list_type": 0},
    "Gmm": {"bias": None, "group_list": None, "group_type": 0, "group_list_type": 0},
    "GmmV2": {"bias": None, "group_list": None, "group_type": 0, "group_list_type": 0},
    "MoeTokenUnpermute": {"probs": None, "padded_mode": False, "restore_shape": None},
    "GmmBackwardFusion": {"group_list": None, "group_list_type": 0},
    "GmmV2BackwardFusion": {"group_list": None, "group_list_type": 0},
    "AnyExt": {"keepdim": False},
    "FuncMaxPool2D": {"stride": None, "padding": 0, "dilation": (1, 1), "ceil_mode": False, "return_indices": False},
    "GmmV2Backward": {"group_list": None, "group_list_type": 0},
    "DeprecatedProd": {"dim": None, "keepdim": False, "dtype": None},
    "DeprecatedIndexAdd": {"use_lock": True, "check_index_bound": True},
    "DeprecatedCumsum": {"axis": None, "dtype": None},
    "DeprecatedHistc": {"bins": 100, "min": 0, "max": 0},
    "DeprecatedStd": {"axis": None, "ddof": 0, "keepdims": False},
    "DeprecatedChunk": {"axis": 0},
    "DeprecatedUnstack": {"dim": 0},
    "DeprecatedTranspose": {"axes": None},
    "DeprecatedRoll": {"dims": None},
    "DeprecatedVar": {"axis": None, "ddof": 0, "keepdims": False},
    "DeprecatedAllclose": {"rtol": 1e-05, "atol": 1e-08, "equal_nan": False},
    "DeprecatedAddmm": {"beta": 1, "alpha": 1},
    "DeprecatedReduceAll": {"dim": None, "keepdim": False},
    "DeprecatedTril": {"diagonal": 0},
    "DeprecatedGather": {"batch_dims": 0},
    "DeprecatedRepeatInterleave": {"dim": None},
    "DeprecatedAddbmm": {"beta": 1, "alpha": 1},
    "DeprecatedFlatten": {"order": 'C', "start_dim": 0, "end_dim": -1},
    "DeprecatedCountNonzero": {"axis": (), "keep_dims": False, "dtype": None},
    "DeprecatedAddmv": {"beta": 1, "alpha": 1},
    "DeprecatedMin": {"axis": None, "keepdims": False, "initial": None, "where": True, "return_indices": False},
    "DeprecatedLogsumexp": {"keepdim": False},
    "DeprecatedMax": {"axis": None, "keepdims": False, "initial": None, "where": True, "return_indices": False},
    "DeprecatedDiv": {"rounding_mode": None},
    "DeprecatedReduceAny": {"axis": None, "keep_dims": False},
    "DeprecatedMean": {"axis": None, "keep_dims": False},
    "DeprecatedArgsort": {"axis": -1, "descending": False},
    "DeprecatedIsclose": {"rtol": 1e-05, "atol": 1e-08, "equal_nan": False},
    "DeprecatedArgmin": {"axis": None, "keepdims": False},
    "DeprecatedNansum": {"axis": None, "keepdims": False, "dtype": None},
    "DeprecatedArgmax": {"axis": -1, "keepdims": False},
    "DeprecatedTopk": {"dim": None, "largest": True, "sorted": True},
    "DeprecatedBincount": {"weights": None, "minlength": 0},
    "DeprecatedMedian": {"axis": -1, "keepdims": False},
    "DeprecatedSort": {"axis": -1, "descending": False},
    "DeprecatedUnique": {"sorted": True, "return_inverse": False, "return_counts": False, "dim": None},
    "DeprecatedSum": {"axis": None, "dtype": None, "keepdims": False, "initial": None},
    "DeprecatedTake": {"axis": None, "mode": 'clip'},
    "DeprecatedBaddbmm": {"beta": 1, "alpha": 1},
    "DeprecatedSplit": {"axis": 0},
}

op_labels = {
    "InplaceTanh": {"side_effect_mem": True},
    "DistCommReduce": {"side_effect_mem": True},
    "KvScaleCache": {"side_effect_mem": True},
    "InplaceAddmm": {"side_effect_mem": True},
    "Assign": {"side_effect_mem": True},
    "SplitWithSizeView": {"side_effect_mem": True},
    "InplaceRemainderTensorScalar": {"side_effect_mem": True},
    "BatchNormElemt": {"side_effect_mem": True},
    "InplaceNormal": {"side_effect_mem": True},
    "InplaceDivMods": {"side_effect_mem": True},
    "InplaceSiLU": {"side_effect_mem": True},
    "InplaceUniform": {"side_effect_mem": True},
    "ResizeD": {"mode": 'linear'},
    "DropoutGenMaskExt": {"side_effect_hidden": True},
    "SplitTensorView": {"side_effect_mem": True},
    "InplaceReLU": {"side_effect_mem": True},
    "SilentCheckV2": {"side_effect_mem": True},
    "AssignAdd": {"side_effect_mem": True},
    "Dropout": {"side_effect_hidden": True},
    "EmbeddingApplyAdamW": {"_process_node_engine_id": 'PS'},
    "InplaceMul": {"side_effect_mem": True},
    "InplaceDiv": {"side_effect_mem": True},
    "InplaceMuls": {"side_effect_mem": True},
    "ApplyAdamW": {"side_effect_mem": True},
    "InplaceExp": {"side_effect_mem": True},
    "InplacePut": {"side_effect_mem": True},
    "InplaceMaskedFillScalar": {"side_effect_mem": True},
    "InplaceSubExt": {"side_effect_mem": True},
    "EmbeddingApplyAdaGrad": {"_process_node_engine_id": 'PS'},
    "BatchNormGatherStatsWithCounts": {"side_effect_mem": True},
    "DiagonalView": {"side_effect_mem": True},
    "BroadcastToView": {"side_effect_mem": True},
    "AssignSub": {"side_effect_mem": True},
    "InplaceScatterSrc": {"side_effect_mem": True},
    "SilentCheckV3": {"side_effect_mem": True},
    "MlaPreprocess": {"side_effect_mem": True},
    "InplaceMatmulAdd": {"side_effect_mem": True},
    "ChunkView": {"side_effect_mem": True},
    "InplaceScatterValue": {"side_effect_mem": True},
    "AdamW": {"side_effect_mem": True},
    "EmbeddingApplyAdam": {"_process_node_engine_id": 'PS'},
    "InplaceErfinv": {"side_effect_mem": True},
    "TransposeView": {"side_effect_mem": True},
    "InplaceIndexPut": {"side_effect_mem": True},
    "InplaceScatterSrcReduce": {"side_effect_mem": True},
    "InplaceBernoulliScalar": {"side_effect_mem": True},
    "InplaceCopy": {"side_effect_mem": True},
    "InplaceRemainderTensorTensor": {"side_effect_mem": True},
    "InplaceScatterValueReduce": {"side_effect_mem": True},
    "DropoutExt": {"side_effect_hidden": True},
    "Log": {"cust_aicpu": 'Log', "base": -1.0, "scale": 1.0, "shift": 0.0},
    "EmbeddingApplySgd": {"_process_node_engine_id": 'PS'},
    "DistCommAllReduce": {"side_effect_mem": True},
    "InplaceFillDiagonal": {"side_effect_mem": True},
    "TransposeExtView": {"side_effect_mem": True},
    "SelectExtView": {"side_effect_mem": True},
    "NarrowView": {"side_effect_mem": True},
    "UnstackExtView": {"side_effect_mem": True},
    "InplaceScatterAdd": {"side_effect_mem": True},
    "SliceExtView": {"side_effect_mem": True},
    "InplaceLog": {"side_effect_mem": True},
    "InplaceFloor": {"side_effect_mem": True},
    "Embedding": {"side_effect_mem": True},
    "InplaceGroupedMatmulAdd": {"side_effect_mem": True},
    "InplaceFloorDivide": {"side_effect_mem": True},
    "EmbeddingApplyRmsprop": {"_process_node_engine_id": 'PS'},
    "InplaceElu": {"side_effect_mem": True},
    "InplaceFloorDivides": {"side_effect_mem": True},
    "InplaceIndexAddExt": {"side_effect_mem": True},
    "InplaceBernoulliTensor": {"side_effect_mem": True},
    "EmbeddingApplyFtrl": {"_process_node_engine_id": 'PS'},
    "ExpandDimsView": {"side_effect_mem": True},
    "InnerInplaceIndexPut": {"side_effect_mem": True},
    "GroupTopk": {"side_effect_mem": True},
    "AdamWeightDecay": {"side_effect_mem": True},
    "InplaceDivMod": {"side_effect_mem": True},
    "InplaceDivs": {"side_effect_mem": True},
    "InplaceRandom": {"side_effect_mem": True},
    "EmbeddingTableEvict": {"_process_node_engine_id": 'PS'},
    "ReshapeAndCache": {"side_effect_mem": True},
    "InplaceFillTensor": {"side_effect_mem": True},
    "InplaceHardtanh": {"side_effect_mem": True},
    "InplaceThreshold": {"side_effect_mem": True},
    "InplaceSubScalar": {"side_effect_mem": True},
    "InplaceAddsExt": {"side_effect_mem": True},
    "Generator": {"side_effect_mem": True},
    "InplaceFillScalar": {"side_effect_mem": True},
    "InplaceAddExt": {"side_effect_mem": True},
    "InplaceMaskedFillTensor": {"side_effect_mem": True},
    "KVCacheScatterUpdate": {"side_effect_mem": True},
    "InplaceExponential": {"side_effect_mem": True},
}
