# Generated by Django 4.2.9 on 2024-12-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0044_remove_dagmodel_trigger_url_expected_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowmodel',
            name='workflow_type',
            field=models.CharField(choices=[('simple_httpoperators_sequential_with_condition', 'chain the endpoints but initialize with a condition to be checked in order for it to begin running'), ('simple_httpoperators_sequential_run', 'chain the endpoints and run them sequentially in a linear fashion'), ('simple_httpoperators_parallel_run', 'chain the endpoints and run them in a parallel manner')], default='simple_httpoperators_sequential_run', max_length=255),
        ),
    ]
