# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pynput import keyboard, mouse
from pynput.keyboard import Key, KeyCode, Listener
from pynput.mouse import Button
from typing import Any
from typing_extensions import Self
import threading
import time
import tkinter

class CaptureApp:
    def __init__(self: Self) -> None: ...
    def create_widgets(self: Self) -> Any: ...
    def log_output(self: Self, message: Any) -> Any: ...
    def on_key_press(self: Self, key: Any) -> Any: ...
    def on_key_release(self: Self, key: Any) -> Any: ...
    def on_click(self: Self, x: Any, y: Any, button: Any, pressed: Any) -> Any: ...
    def start_listeners(self: Self) -> Any: ...
    def stop_listeners(self: Self) -> Any: ...
    def on_closing(self: Self) -> Any: ...
    def run(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import tkinter
import pynput
import pynput.mouse
import pynput.keyboard
import threading
import time