# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: soil_services/AxialSoilService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'soil_services/AxialSoilService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$soil_services/AxialSoilService.proto\x12\x0fgrpc_axial_soil\":\n\x13GetAxialSoilRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07soil_id\x18\x02 \x01(\t\"V\n\x14GetAxialSoilResponse\x12>\n\x10\x61xial_soil_props\x18\x01 \x01(\x0b\x32$.grpc_axial_soil.AxialSoilProperties\"\x8c\x01\n\x13SetAxialSoilRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x0f\n\x07soil_id\x18\x03 \x01(\t\x12>\n\x10\x61xial_soil_props\x18\x04 \x01(\x0b\x32$.grpc_axial_soil.AxialSoilProperties\"\x16\n\x14SetAxialSoilResponse\"N\n\x13\x41xialSoilProperties\x12\x37\n\x0f\x61xial_soil_type\x18\x01 \x01(\x0e\x32\x1e.grpc_axial_soil.AxialSoilType*\xf4\x01\n\rAxialSoilType\x12\x1a\n\x16\x41XIAL_TYPE_UNSPECIFIED\x10\x00\x12\x12\n\x0e\x45_SAND_TZ_PILE\x10\x01\x12\x12\n\x0e\x45_CLAY_TZ_PILE\x10\x02\x12\x1a\n\x16\x45_USER_DEFINED_TZ_PILE\x10\x03\x12\x10\n\x0c\x45_TZ_ELASTIC\x10\x04\x12\x1e\n\x1a\x45_COYLE_REESE_CLAY_TZ_PILE\x10\x05\x12\x19\n\x15\x45_MOSHER_SAND_TZ_PILE\x10\x06\x12\x1a\n\x16\x45_DRILLED_CLAY_TZ_PILE\x10\x07\x12\x1a\n\x16\x45_DRILLED_SAND_TZ_PILE\x10\x08\x32\xe4\x01\n\x10\x41xialSoilService\x12g\n\x16GetAxialSoilProperties\x12$.grpc_axial_soil.GetAxialSoilRequest\x1a%.grpc_axial_soil.GetAxialSoilResponse\"\x00\x12g\n\x16SetAxialSoilProperties\x12$.grpc_axial_soil.SetAxialSoilRequest\x1a%.grpc_axial_soil.SetAxialSoilResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'soil_services.AxialSoilService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AXIALSOILTYPE']._serialized_start=453
  _globals['_AXIALSOILTYPE']._serialized_end=697
  _globals['_GETAXIALSOILREQUEST']._serialized_start=57
  _globals['_GETAXIALSOILREQUEST']._serialized_end=115
  _globals['_GETAXIALSOILRESPONSE']._serialized_start=117
  _globals['_GETAXIALSOILRESPONSE']._serialized_end=203
  _globals['_SETAXIALSOILREQUEST']._serialized_start=206
  _globals['_SETAXIALSOILREQUEST']._serialized_end=346
  _globals['_SETAXIALSOILRESPONSE']._serialized_start=348
  _globals['_SETAXIALSOILRESPONSE']._serialized_end=370
  _globals['_AXIALSOILPROPERTIES']._serialized_start=372
  _globals['_AXIALSOILPROPERTIES']._serialized_end=450
  _globals['_AXIALSOILSERVICE']._serialized_start=700
  _globals['_AXIALSOILSERVICE']._serialized_end=928
# @@protoc_insertion_point(module_scope)
