# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from soil_services import LateralPiedmontService_pb2 as soil__services_dot_LateralPiedmontService__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in soil_services/LateralPiedmontService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LateralPiedmontServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPiedmontProperties = channel.unary_unary(
                '/grpc_lateral_piedmont.LateralPiedmontService/GetPiedmontProperties',
                request_serializer=soil__services_dot_LateralPiedmontService__pb2.GetPiedmontRequest.SerializeToString,
                response_deserializer=soil__services_dot_LateralPiedmontService__pb2.GetPiedmontResponse.FromString,
                _registered_method=True)
        self.SetPiedmontProperties = channel.unary_unary(
                '/grpc_lateral_piedmont.LateralPiedmontService/SetPiedmontProperties',
                request_serializer=soil__services_dot_LateralPiedmontService__pb2.SetPiedmontRequest.SerializeToString,
                response_deserializer=soil__services_dot_LateralPiedmontService__pb2.SetPiedmontResponse.FromString,
                _registered_method=True)


class LateralPiedmontServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPiedmontProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPiedmontProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LateralPiedmontServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPiedmontProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPiedmontProperties,
                    request_deserializer=soil__services_dot_LateralPiedmontService__pb2.GetPiedmontRequest.FromString,
                    response_serializer=soil__services_dot_LateralPiedmontService__pb2.GetPiedmontResponse.SerializeToString,
            ),
            'SetPiedmontProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPiedmontProperties,
                    request_deserializer=soil__services_dot_LateralPiedmontService__pb2.SetPiedmontRequest.FromString,
                    response_serializer=soil__services_dot_LateralPiedmontService__pb2.SetPiedmontResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_lateral_piedmont.LateralPiedmontService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc_lateral_piedmont.LateralPiedmontService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LateralPiedmontService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPiedmontProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_lateral_piedmont.LateralPiedmontService/GetPiedmontProperties',
            soil__services_dot_LateralPiedmontService__pb2.GetPiedmontRequest.SerializeToString,
            soil__services_dot_LateralPiedmontService__pb2.GetPiedmontResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPiedmontProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_lateral_piedmont.LateralPiedmontService/SetPiedmontProperties',
            soil__services_dot_LateralPiedmontService__pb2.SetPiedmontRequest.SerializeToString,
            soil__services_dot_LateralPiedmontService__pb2.SetPiedmontResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
