STYLISTS_WORDS = [
"hair",
"appointment",
"appointments",
"book",
"call",
"book.thecut.co",
"licensed",
"cutz",
"kutz",
"cuts",
"cut",
"hairstylist",
"salon",
"salons",
"educator",
"specialist",
"beauty",
"barber",
"walk",
"text",
"stylist",
"colour",
"colouring",
"loreal",
"olaplex",
"hairspray",
"mousse",
"pomade",
"hair oil",
"hair serum",
"scissors",
"comb",
"brush",
"blow dryer",
"flat iron",
"curling iron",
"hair rollers",
"hair clips",
"hair ties",
"headbands",
"hair accessories",
"updos",
"braids",
"twists",
"buns",
"ponytails",
"curls",
"waves",
"volume",
"texture",
"shine",
"frizz control",
"breakage",
"dryness",
"oiliness",
"thinning",
"hair loss",
"dandruff",
"scalp problems",
]

STYLISTS_NEGATIVE_WORDS=[
    "booksy", "Supplier", "Supply", "supplies", "manufacturer", "wholesaler", "shipping", "dentist ", "Massage Therapist", "Therapist", "onlyfans" 
]

JAMEL_POSITIVE_KEYWORDS = ["ceo",
 "coo",
 "alumni",
 "owner",
 "founder",
 "co-founder",
 "coach",
 "trucking",
 "truck",
 "entrepreneur",
 "founder",
 "boss",
 "business owner",
 "operator",
 "real estate",
 "realtor",
 "e-commerce",
 "e-comm",
 "ecomm",
 "dropshipping",
 "amazon",
 "reseller",
 "whatnot",
 "fitness trainer",
 "online trainer",
 "personal trainer",
 "airbnb",
 "airbnb host",
 "house flipper",
 "fix and flip",
 "fix n flip",
 "fix & flip",
 "lashes",
 "brows",
 "micro smp",
 "tatoo artist",
 "medspa",
 "auto repair",
 "sneaker retailer",
 "etsy",
 "ebay",
 "e-bay",
 "mindbody",
 "pma",
 "permanent makeup artists",
 "licensed",
 "certified",
 "micro-pigmentation artist",
 "micro pigmentation",
 "supplier",
 "temu.com",
 "pmu",
 "permanent makeup expert",
 "trainer",
 "coach",
 "online coach",
 "fitness coach",
 "artist",
 "brow",
 "smp",
 "wigs",
 "hair extensions",
 "hair bundles",
 "beauty",
 "cosmetic",
 "personal care",
 "alum",
 "success",
 "earner",
 "winner",
 "award",
 "graduate",
 "mba",
 "jd",
 "phd.",
 "author",
 "automotive",
 "construction",
 "building",
 "design",
 "retail",
 "accounting",
 "home services",
 "landscaping expert",
 "gardening expert",
 "events",
 "marketing expert",
 "design agency",
 "medical",
 "wellness",
 "real estate",
 "property manager",
 "transportation",
 "logistics",
 "veterinary",
 "accounting",
 "bookkeeping",
 "architect",
 "car dealer",
 "repair shop",
 "car repair",
 "carpenter",
 "chiropractor",
 "courier",
 "logistics",
 "dance teacher",
 "day care",
 "dentists",
 "electrician",
 "event planner",
 "event coordinator",
 "flooring",
 "florist",
 "food delivery",
 "catering",
 "furniture repair",
 "hvac technician",
 "hair salon",
 "painter",
 "contractor",
 "inspector",
 "home service",
 "independent",
 "insurance agent",
 "interior designer",
 "managed services",
 "laser clinic",
 "locksmith",
 "mover",
 "music teacher",
 "nail salon",
 "au pair services",
 "supplies",
 "rental",
 "services",
 "pest control",
 "photographer",
 "plumber",
 "pool technician",
 "hot tub technician",
 "print shop",
 "property manager",
 "public relations",
 "real estate agent",
 "refinishing service",
 "roofer",
 "social media marketing",
 "agency",
 "solar energy business",
 "spa",
 "tattoo shop",
 "piercing studio",
 "taxi service",
 "travel agent",
 "trucking",
 "logistics business",
 "tutor",
 "veterinary",
 "pet services",
 "wedding planner",
 "event planner"
 ]
 
JAMEL_NEGATIVE_KEYWORDS=["bitch",
 "funding",
 "credit repair",
 "credit restoration",
 "inquiry removal",
 "inquiries removal"
]