# This file was auto-generated by Fern from our API Definition.

from .....core.pydantic_utilities import UniversalBaseModel
from .ec_2_security_groups_enumerate_result import Ec2SecurityGroupsEnumerateResult
from .ec_2_security_groups_enumerate_config import Ec2SecurityGroupsEnumerateConfig
import typing
from .....core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class Ec2SecurityGroupsEnumerateReport(UniversalBaseModel):
    result: Ec2SecurityGroupsEnumerateResult
    config: Ec2SecurityGroupsEnumerateConfig
    errors: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.allow
