# Generated by Django 4.2.9 on 2024-11-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0002_rename_dataentry_databasecred'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chart_type', models.CharField(choices=[('line', 'Line'), ('bar', 'Bar'), ('pie', 'Pie')], default='line', max_length=200)),
                ('query', models.TextField()),
            ],
        ),
    ]
