from setuptools import setup, find_packages

setup(
    name='ftgo',
    version='1.0.0',
    packages=find_packages(),
    install_requires=[
        'cloudscraper>=1.2.68',
        'pandas>=1.3.0',
        'beautifulsoup4>=4.11.0',
    ],
    author='gohibiki',
    author_email='gohibiki@protonmail.com',
    description='A Python library for fetching financial data from FT Markets',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/gohibiki/ftgo',
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Financial and Insurance Industry',
        'Intended Audience :: Developers',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Topic :: Office/Business :: Financial',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
    python_requires='>=3.7',
    keywords='finance stocks etf historical-data market-data ft-markets financial-times',
)