# coding: utf-8

"""
    searcher

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.3.6
    Contact: kaka@cingta.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from searcher_py_async.models.default_response_vec_search_detail_string import DefaultResponseVecSearchDetailString

class TestDefaultResponseVecSearchDetailString(unittest.TestCase):
    """DefaultResponseVecSearchDetailString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefaultResponseVecSearchDetailString:
        """Test DefaultResponseVecSearchDetailString
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefaultResponseVecSearchDetailString`
        """
        model = DefaultResponseVecSearchDetailString()
        if include_optional:
            return DefaultResponseVecSearchDetailString(
                state = 0,
                data = [
                    null
                    ],
                error = ''
            )
        else:
            return DefaultResponseVecSearchDetailString(
                state = 0,
        )
        """

    def testDefaultResponseVecSearchDetailString(self):
        """Test DefaultResponseVecSearchDetailString"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
