# coding: utf-8

"""
    Kadoa API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Contact: support@kadoa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v4_crawl_session_id_pages_get200_response_payload_inner import V4CrawlSessionIdPagesGet200ResponsePayloadInner

class TestV4CrawlSessionIdPagesGet200ResponsePayloadInner(unittest.TestCase):
    """V4CrawlSessionIdPagesGet200ResponsePayloadInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V4CrawlSessionIdPagesGet200ResponsePayloadInner:
        """Test V4CrawlSessionIdPagesGet200ResponsePayloadInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V4CrawlSessionIdPagesGet200ResponsePayloadInner`
        """
        model = V4CrawlSessionIdPagesGet200ResponsePayloadInner()
        if include_optional:
            return V4CrawlSessionIdPagesGet200ResponsePayloadInner(
                id = '',
                url = '',
                status = 'DONE'
            )
        else:
            return V4CrawlSessionIdPagesGet200ResponsePayloadInner(
        )
        """

    def testV4CrawlSessionIdPagesGet200ResponsePayloadInner(self):
        """Test V4CrawlSessionIdPagesGet200ResponsePayloadInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
